### ISSUE TITLE
Task - OTU radial - biological association.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1012]
1. I created one biological association from a particular source. It is properly saved with a citation
2. I trying to create a second association for the same taxon from the same source (without reloading the OTU radial). The association is saved, but the citation is not created.

**Comment by jlpereira** [comment]
The problem here is when you create a biological association the citation is removed but this is not reflected in the interface. Thats the reason why when you create a new one the citation is not added even when you see it on the citation section.

@mjy @proceps what do you want here? clean the interface or leave the citation there after a biological association is created?

**Comment by mjy** [comment]
@jlpereira Clean it on create

**Comment by proceps** [comment]
For me, preffered solution both here and in distribution section would be to add a lock icon to lock the source...
