### ISSUE TITLE
questions related to homonym (new species name)

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1019]
I added the new taxon Conocephalus (Anisoptera) brevis Farooqi & Usmani, 2019. This is a primary homonym of Conocephalus brevis Redtenbacher 1891 (now Neoconocephalus brevis), which TW recognized. I then created the homonym relationship. Several things are unclear to me:

1) Although it is a homonym, the name is accepted as valid.

2) When I select Status "homonym", I'm asked to specify whether it is a primary or a secondary homonym. I cannot find how to do this.

3) When I also select Status "temporary name", this confusing comment appears: 
![imagen](https://user-images.githubusercontent.com/33210201/62636010-27822780-b90f-11e9-8a0d-397f1c8e33f6.png)
(How can the very same name be valid and invalid?)

4) When I go to edit the taxon, the validation says that status "temporary name" is conflicting with status "homonym". But the name should be temporary as long as there is no substitute name.

5) At the beginning, when I added the taxon name,  I was also suggested to remove the Status "homonym" and replace it with the relationship to the senior homonym (which I had already entered), this message including the misspelling "Prymary Homonym". At the moment I cannot reproduce this.

**Comment by proceps** [comment]
To properly handle homonym, you have to create two taxon name relationships:
1. Homonym relationship, start with junior homonym, and create a primary or secondary homonym relationship to the senior homonym.
2. Synonym relationship, start from the same name a select a valid name for this species. The relationship could be a "Synonym" or "replaced by"
The message you have only indicate that you have not completed the relationships for the taxon. Since the name is a homonym, it is not a valid name, but since the valid name is not provided, it can only point to itself.
Using the status of Homonym is not recommended, because it does not provide proper explicit indication of the name which causes the homonymy. This is also a source of validation. When you say that the name is a primary homonym, the TW checks if two names were actually described in the same genus.
I will check for the misspelling.

**Comment by typophyllum** [comment]
Thank you. Now I found "primary homonym" among the list shown in the Relationship section. Perhaps a little bit confusing that "Homonym" is also offered in the Status section. Currently there is no valid name for this junior homonym (in OSF it is a temporary name and I sent the author an e-mail informing him that it needs a substitute name).

Now I created the fictitious species Conocephalus (Anisoptera) brunneri Farooqi & Usmani, 2019, which would be a primary homonym of Conocephalus brunneri Redtenbacher 1891 (now also in Neoconocephalus). But here appears this message:
![imagen](https://user-images.githubusercontent.com/33210201/62654440-29131600-b936-11e9-964e-fe4125dfac81.png)

**Comment by proceps** [comment]
homonym status created primary for the data migration, when I do not have information about senior homonym. It is intended as a temporary solution before the proper relationship is not created.
This message is a bug, I believe it is only in test version of the database. I believe it is already resolved in production. It intend to catch cases where the names are completely different, so they should not be treated as homonyms.

**Comment by mjy** [comment]
@proceps Can you please copy this question, in the form of an answer, to taxonworks_doc? THere are other questions in this vein answered there.  @typophyllum feel free to ask questions there as well, though here is fine to if you're not sure where feedback best fits. - Thank!
