### ISSUE TITLE
Otus to OTUs

### ISSUE THREAD

**Issue by ianengelbrecht** [SpeciesFileGroup/taxonworks#1048]
**Describe the bug**

A small update suggestion: Otus is presumably Operational Taxonomic Units. As an abbreviation it should be capitalized. On first visiting the site the user sees this as Otus, which may be confusing. Otus is after all a genus of owls :-)

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production

**Comment by mjy** [comment]
Thanks @ianengelbrecht.  I agree, but we might be constrained by the "automatic" nature of how everything is plugged together.  

I.e. - in some cases we can change 'Otu' to 'OTU' where we use the string in headers, etc. in the user interface in a custom manner.  In numerous other cases, however, the string is generated automatically according to framework we're building TaxonWorks in.  In this case the actual table is inspected, and code follows a convention for capitalization etc.  To overcome this we would need to write exceptions in many places.

So- definitely something we will strive to make consistenent as possible, however there may "practical" constraints.

Hope this makes sense, and thanks so much for filing an issue!

p.s. I'm going to remove "bug", as that label is intended to indicate something is broken that impedes the application itself from working, rather than just confusing the heck out of folks.  Hope this too makes sense.

**Comment by proceps** [comment]
Please open issue for specific interfaces where it should be changed.

**Comment by debpaul** [comment]
@LocoDelAssembly @mjy isnt' there a way to do a case-sensitive search for all strings "(Otu, otu, Otus)" and replace them with "OTU" or "OTUs" Seems hard to suggest we need to do this interface-page-by-page?

**Comment by mjy** [comment]
@debpaul much of the interface is dynamic, it's not quite as easy as that change.  For example we generate labels for some things be inferring from their models.
