### ISSUE TITLE
Task - Collection Object Filter - Verbatim collectors and Collector facet

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1315]

**Comment by tmcelrath** [comment]
Just to confirm, this issue isn't closed because we still need a filter by Collector facet correct? If so I would like to upvote this issue. 

E.g. I can search text in "buffered collecting event" and in "verbatim collector" fields right now, but I cannot select a person assigned as a collector and get all the COs where they were assigned as a collector role.

**Comment by mjy** [comment]
@tmcelrath I think you are correct.  @jlpereira Let's prioritize this.  Role picker for Collectors in this task. We need to nest the params in the CollectingEvent (hoping we have that facet in CE filter already).
