### ISSUE TITLE
Task - Browse nomenclature - Part of speech

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1366]
When I select adjective or participle part of speech, three forms of the name are not offered any more. This feature worked in the past.

**Comment by jlpereira** [comment]
<img width="886" alt="Captura de Pantalla 2020-03-17 a la(s) 10 10 48" src="https://user-images.githubusercontent.com/16530364/76859313-d25cab80-6837-11ea-8fe8-9aa26ef4dfdb.png">
<img width="893" alt="Captura de Pantalla 2020-03-17 a la(s) 10 10 59" src="https://user-images.githubusercontent.com/16530364/76859314-d38dd880-6837-11ea-9770-851859167dbc.png">

I can't replicate it

**Comment by proceps** [comment]
Yes, exactly, you have empty boxes on the image, they have to be populated with 3 alternative values. And it worked in the past.

**Comment by mjy** [comment]
@proceps You have to provide steps to replicate.  *FULL* steps.

**Comment by proceps** [comment]
1. Enter the name which is adjective
2. Select adjective as a part of speech.
3. See empty boxes (which have to be prepopulated with alternative values).

**Comment by proceps** [comment]
4. when noun is selected the values have to be deleted. 

All this was implemented in the past. Now it does not work.

**Comment by jlpereira** [comment]
<img width="416" alt="Captura de Pantalla 2020-03-17 a la(s) 10 39 57" src="https://user-images.githubusercontent.com/16530364/76861820-ed311f00-683b-11ea-861c-282219b5ae71.png">

Backend issue, after create the classification and retrieving the taxon name, those fields comes with null value

**Comment by mjy** [comment]
That isn't the full steps.  You have to assume the database is empty.

**Comment by proceps** [comment]
Please see past issues: #194. This was resolved and was working properly until 2-3 month ago.

**Comment by jlpereira** [comment]
I found the issue, its updating taxon name after create the classification, thats the reason why its setting null as value. Fixing

**Comment by mjy** [comment]
To wrap this up: 

*  #194 also does not include steps to replicate the problem (i.e. you have to *create and provide endings for a preceeding name first*).
* If you want faster development then you can help by providing exact steps so that developers don't have to experiment.  THe better your steps, the faster we are.  
* Statements like "it worked before" hint that we understand everythign that the software does, this simply is impossible at this point, it doesn't help.
* If you want to help ensure something that is important never breaks you can help by adding feature specs that test the feature in question (if it is not covered).  This is a fairly safe investment of time for yellow tasks.  There are many examples you can learn from.
