### ISSUE TITLE
Enhancement - grid digitizer - match identifiers to ones currently in system and add depiction to current collection objects

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1383]
If I am using the grid digitizer and add identifiers to what is being grid digitized - then a check should run to see if those identifiers are already in use. If found - an option should be given to add the depiction to the current collection object instead of blocking the depictions from being created.

**Comment by mjy** [comment]
We will modify the code to always look for an existing match on creation, and not fail if one is found.

**Comment by mjy** [comment]
Done, just waiting for comment from @tmcelrath (see gitter).

**Comment by mjy** [comment]
For record tags, determinations, and notes are not added to existing objects lest they are duplicates and break the process.  The thought is: 

1 - Images are intended to have verbatim info in this workflow
2 - because of this, I we only add the depiction to exsting object
because 3 - all really critical information will be there
and 4 - interruptions because of duplicated data will minimized
