### ISSUE TITLE
Task Comprehensive - Create namespace in place

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1422]
I'd like to create a new namespace in place

**Comment by mjy** [comment]
Thanks for the issue. We discussed a number of improvements along these lines last Tuesday in our digitization webinar.  Since Namespaces are relatively rarely created we likely won't do it in place, but we will likely create a new task that let's you create them more easily, perhaps deriving them from Repository codens that are similar.  We'll update the general identifier component to include a link out to that task, so it will be quicker to access if needed.

**Comment by mjy** [comment]
@jlpereira for the time being let's add a "New" link somewhere tucked away on the identifier component.
