### ISSUE TITLE
Citations by source: yellow triangle

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1498]
I absolutely love the "Citations by source" tool -- it improves productivity and allows a thorough checking of incorrect entries. Good job in conceiving this one!

Now, I dunno whether this is a bug, or something I have done wrong:

(1) I registered the species _Opilio parietinus_ (De Geer, 1778).

(2) When doing so, I also registered that this species was originally combined with genus _Phalangium_.

(3) Then I explicitly registered who made this combination with _Opilio_, which was Herbst (1798), 20 years after the original description.

So far, so good:

here: https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=322616
![image](https://user-images.githubusercontent.com/46284943/82222020-1ed76c80-98f7-11ea-9c32-dce87cb872ff.png)

However, when I look at the "Citations by source" page, the name _Opilio parietinus_ appears with a yellow triangle warning written "Invalid". 
There shouldn't have anything invalid here, and I wonder whether this message is an error. 

here: https://sfg.taxonworks.org/tasks/nomenclature/by_source?source_id=11232

![image](https://user-images.githubusercontent.com/46284943/82222294-77a70500-98f7-11ea-80ca-9c76766ca7b9.png)

**Comment by proceps** [comment]
@adrik29 only protonyms may have status of valid or invalid (based on the nomeclatural status and/or TaxonNameRelationships). Combinations itself, never considered a valid name, it is treated as a historical usage of the particular protonym. In many places in TW I need a way to indicate that the name cited is a protonym or combination, valid or invalid. Because sometimes the combination and protonym has exactly the same spelling. So this triangle, does not have any special warning, it only an indication, that the name is not a protonym, or if it is a protonym, it is not a valid name (sometimes, I have a nomen nudum linked to a protonym with exactly the same spelling). So, @mjy, may be the triangle is not a good symbol and should be replaced with a green check mark for valid names (as in some other interfaces).

**Comment by mjy** [comment]
Agreed, we should change it to reflect the check, C or X like we have in
autocomplete?

**Comment by adrik29** [comment]
The problem is that when your your hover over the triangle, the word "invalid" appears. I was puzzled, because the combination Opilio parietinus should be OK. And yes, combinations are not valid or invalid, only protonyms. Combinations are current/accepted (kyronyms) or not.

And while we are at it -- I understand that the **kyronym** ("accepted" or "correct" name, sensu Dubois) in TW is defined by setting the parent.
In this particular case I set _Opilio_ as the parent of _parietinus_, so the system "knows" that _Opilio parietinus_ is the accepted combination (kyronym) _contra_ the original _Phalangium parietinum_.

But on the other hand, this method of setting the parent may create combinations that never existed. In the case of a species Cus xus which is a junior subjective synonym of Bus yus.
I am forced by TW to set Bus as the parent of xus, which creates the non-existing combination Bus xus.

**Comment by proceps** [comment]
Yes, this is non existing combination. But you do not see this combination in the Browse nomenclature.
But you remember this combination compete for secondary homonymy with other names, even so it was never specifically cited in this form. Once the species put into synonymy to another species (from different genus), it is considered that this name also moved into this new genus.
ICZN is more flexible on setting new combinations compared to ICN. In botany, publication of new "combinations" is a required nomenclatural act. In zoology, on the other hand this is only classification. So nothing restricts me from creating new combinations in the database. For example, somebody put two names of genera into synonymy. But did not specifically mentioned any new combination. I can safely assume, that at least type species of a younger synonym was moved into different genus, and create this new combination.

**Comment by adrik29** [comment]
Dmitry, you raised another vexing problem that I face:
 
Someone synonymizes genus Bus Roewer 1930 with genus Aus Simon 1880 mentioning only the type-species.
Genus Bus had 50 species, and the type-species now goes as Aus xus (Doe, 1799), but what about the other 49 species? They were not formally combined under Aus.
And we cannot assume that who made the synonymy also considers each one of them to belong to Aus, they could well belong to Cus, Dus, Eus...
This is a taxonomic, not nomenclatural decision.
So, what do we catalogers do?
I cannot simply let a species name attached to an invalid genus...
And I cannot combine the other 49 species under Aus in my TW catalog which is NOT a publication (because it doesn't have a fixed date, the changing of content being continuous).

**Comment by proceps** [comment]
Hi, Adriano, In most case, I simply move the species to Aus, but do not create new combinations (except for the type species). One can argue, that the species could belong to various different genera. But assume a situation where the same author actually mentioned 50 combinations, but as a database curator you know that those species probably belong to 5 different genera. What would you do. For me, it does not really matter, this is only a catalog, and we try to present the best of our knowledge. You still have to wait for the next revision to move the species around. If you want to be very precise, you can, of cause, create incertae sedis. Move species to the tribe (or any other higher level). and add Incertae sedis relationship. But practically speaking, I try to avoid this, and only use Incertae sedis only in cases when the author specifically stated in the publication that the species does not belong to a genus, but does not know where it belongs. As I said, in previous message, the ICZN does not require publication of new combinations, so as a curator, you can do whatever you thing is the best for your group. In few cases, I actually ignored the proposed synonymy, if I know that the author did not do the complete revision. I created a new combination for the type species, added proposed synonymy, but at the same time, put a status of valid to the junior synonym, so it will be treated as valid in the database, despite the synonym relationship. I can give you an example if you want.

**Comment by adrik29** [comment]
Very recently I published a paper on genus Paecilaema, which had about 100 species. There were 5 genera erroneously (according to MY taxonomic judgment of course) buried into its synonymy and I revalidated them.
Now, there is only a core of 12 species that are really Paecilaema, and 5 which are the types of the revalidated genera. Apart from these 17 species, what happens to the 80-so species?
I don't know!
They are in Paecilaema right now by sheer inertia, waiting for case by case studies...

This problem is much simpler that the other we were talking about because a given species is (erroneously) linked to a valid genus.

But I cannot just leave a species attached to an invalid genus. 
And, Dmitry, yes, I would love to see an example of how you dealt with the matter.

I obviously cannot review all inclusions of the 7 k species in Opiliones to decide in which genus they should go.

Apart from this, there are zillions of smaller nomenclatural problems that I am unearthing during the preparation of my Opiliones catalogue. For many of them I'm publishing small nomenclatural papers resolving at some level those problems in a formal publication, just because I cannot propose them in my online catalogue (only in a published one).

**Comment by proceps** [comment]
Genus Macuellus was synonymized to the genus Henschia in 2006 in a faunistic work, but there was a large generic revision published few years before (1999) treating it as a valid genus. Henschia is older, but has only 3 valid species. Macuellus has 3 subgenera and about 40 valid species. I cannot just follow 2006 paper, because it includes only one species of Macuellus which was transferred to Henschia. And I know both genera. 
In TW I put a nomenclatural status to Macuellus (valid) and saved the synonymy (as well as new combination for the type species).

Mocuellus Ribaut, 1946b: 83. (valid in Emeljanov, 1999e) Type species by original designation Deltocephalus collinus Boheman, 1850
Mocuellus Ribaut, 1946 (subjective synonym of Henschia Lethierry, 1892) in Holzinger & Kunz, 2006a: 170.

The genus is still valid, the nomenclatural status *valid* prevent synonymy. Of cause I cannot do this for all species in Auchenorrhyncha. And in most cases I just follow the recent treatment, and waiting for another revision to fix the remaining problems. And as I said, I would keep species in the genus before somebody move it out, or specifically state that this species does not belong there. In cases of the generic synonymy, I would move all valid species from one genus to another.
I had few cases where two genera have the same type species. Objective synonyms, but the synonymy was never published. I decided that objective synonymy does not require official publication. And just treat them as synonyms (moving all the species from one genus to another).

**Comment by proceps** [comment]
yellow triangle is removed
