### ISSUE TITLE
annotations metadata (NoMethodError) "undefined method `project_id' for #<GeographicArea:0x00007f6d0e941808>

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1537]
```ruby
2.7.1 :009 > GeographicArea.is_community?
 => true 
2.7.1 :010 > GeographicArea.new.is_community?
 => false 
```
Unsure about proper solution. Add `include Shared::SharedAcrossProjects` to `GeographicArea`? Diff below?
```diff
diff --git a/app/models/concerns/shared/is_data.rb b/app/models/concerns/shared/is_data.rb
index 4ae2ac570..1da81c278 100644
--- a/app/models/concerns/shared/is_data.rb
+++ b/app/models/concerns/shared/is_data.rb
@@ -89,7 +89,7 @@ module Shared::IsData
 
   # @return [Boolean]
   def is_community?
-    self.class < Shared::SharedAcrossProjects ? true : false
+    (self.class.try :is_community?) || (self.class < Shared::SharedAcrossProjects ? true : false)
   end
 
   # @return [Boolean]
```

**Comment by mjy** [comment]
Good question.  I think we should not add shared/shared across projects since `can_destroy` can_edit are never needed. I've' updated the models description.

Question: Why do you need to call GeographicArea.new?  It will only ever be done in rake tasks and not be editable by users.  Users who need to create different GeographicArea type records will do so in a customizable (yet uncreated) Gazetteer model.  I think there are some issues that discuss this.

**Comment by mjy** [comment]
```
3.2.2 :001 > GeographicArea.is_community?
 => true 
3.2.2 :002 > GeographicArea.new.is_community?
 => true 
3.2.2 :003 > 
```
