### ISSUE TITLE
Browse taxa icon can not be opened in new tab

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1550]
When I use my "open in new tab" click on the OTU icon, then my browser opens in the same window.  I believe this is because we hijack the click with an event?

**Comment by jlpereira** [comment]
Im missing something here.  With "open in new tab" you mean  press command key and click in the button?

OTU radial its not a link, so that it wont work. I think we can make it open in a new tab just making a click with the right button, like we do for the slice on the radial navigator. What you think?

**Comment by mjy** [comment]
Sorry, not enough info. Not OTU radial (or annotator), browse icon: 

![Screen Shot 2020-06-17 at 5 28 17 PM](https://user-images.githubusercontent.com/22600/84957057-0908c300-b0c0-11ea-801f-c1a30e6d0034.png)

Yes, I mean command-click to open in new window (or whatever user has).

**Comment by jlpereira** [comment]
Done, right click will open it in a new tab
