### ISSUE TITLE
Task - New taxon name - "Classification" section

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1565]
Create a new section "Classification".

* [ ] Remove set as parent from Relationships, move that functionality to this section
* [ ] Add ability to pick and create SourceClassified as sections

@proceps - other things that belong here?

**Comment by proceps** [comment]
I believe it is only two: Incertae sedis and Source Classified as.
The first one is always identical to Parent.

**Comment by mjy** [comment]
Thanks.  We ill set up the section with those, and go from there if we figure out something new.  @jlpereira You can tackle this now if you want.  In essence we
* duplicate the Relationship section to Classification section and add a second radio button
* Remove the "set as parent" from the Relationship section
* Add the "SourceClassifiedAs" relationship type as an option along with existing incertae option

**Comment by proceps** [comment]
I mean keep "set as parent" in the new section, and remove it from the Relationship section.

**Comment by mjy** [comment]
Yes, definitely!

**Comment by jlpereira** [comment]
Done, let me know if the section is correct or not. Should be filter for a specific rank group?

**Comment by proceps** [comment]
Does not work as it is. Source classified as requires selection of taxa in FAMILY_AND_ABOVE_RANK_NAMES

**Comment by jlpereira** [comment]
@proceps Pushed again, added rank filters.

**Comment by proceps** [comment]
Sorry, my fault. I was not clear in my explanation. The relationships in this section could be assigned to taxa in All Ranks (section should be visible for all protonyms), but the search filter was incorrect. You should be able to search for related taxon in the family and above rank names using the text box. 

Now the section is not visible to species and genera.

**Comment by jlpereira** [comment]
Aha, pushed again.

**Comment by proceps** [comment]
It works, but there are few issues:
1. The label once created the label is slightly incorrect: "As classified for Aboilidae Martynov, 1925". It correctly shows the object, but the status part is wrong, this is the status label for the object not for subject. The label should read "Source classified as Aboilidae Martynov"
2. I can see the relationship only when it is just created, If I reload the page, the relationship does not displayed. (probably the search filter is scoped to object, not subject.
3. I do not see the button "set as parent" it is not visible any more.
4. I cannot see the relationship in Browse nomenclature section. Two option, either it is not saved, that will also explain #2, or it is not properly scoped, and this will be on me to display it. Since the Incertae sedis relationships are displayed there, I suspect that it is not saved.

Once again. Protonym self is a subject in the relationship and it could be of any rank.
Related taxon name is an object, and it could be Family group rank or above (or the parent in case of Incertae sedis). The label should display the relationship status from the subject to object.
So the handling of the section is the same as for the main TaxonNameRelationship section in terms of labels and subject-object relationships. But the related TaxonName search box (object) is restricted to Family and above ranks.

**Comment by mjy** [comment]
I don't *think* we include source classified as in browse nomenclature yet

**Comment by proceps** [comment]
Incertae sedis is included. Don't you thing they are generated the same way? I will check the code. The real problem at the moment that the newly generated relationship is not visible after the edit page is reloaded.

**Comment by jlpereira** [comment]
@proceps 

1- Check this file:  `/app/models/taxon_name_relationship/source_classified_as.rb` line: 27.

I think thats need to be inverted there, because we're using the subject string on the interface, its the same we use for relationships sections.

2- I looked the endpoint we use to retrieve the relationships:
/taxon_names/<id>/taxon_name_relationships?as_subject=true&of_type[]=synonym&of_type[]=status

I think we need another of_type filter for this, right? `/lib/queries/taxon_name_relationships_filter_query.rb` line: 54
I been looking the const name where SourceClasified should be, but I cant found it to add it there

3- As the autocomplete use a filter for family and above ranks, I thought we need to hide this button if the taxon name parent rank was not a family or above. I change it again and now should be visible for any rank, even if the parent is a genus.

4- I didnt take a look yet how we display the relationships there, but maybe could be related with the 1 and 2 points

**Comment by mjy** [comment]
Re display- the inline display in the New taxon form will require of_type[]=`TaxonNameRelationship::SourceClassifiedAs` and another for the incertae class.

@proceps are source classifed as with name = subject and family = object?

**Comment by proceps** [comment]
1. updated status string
2. added additional of_type[]=classification, you can use it to retrieve both relationships.
3. Have to think about it little bit more. Fore me it is only family ranks, but I believe we had an issue previously, somebody wanted to use genus groups for incertae sedis.
4. probably still an issue, I will check what could be done.

**Comment by jlpereira** [comment]
It didnt work `with of_type[]=classification`(missing on taxon_name_relationships_filter_query.rb) or `of_type[]=TaxonNameRelationship::SourceClassifiedAs`

I removed all of_type parameters and leave only as_subject=true, it seems to work fine now. We really need the others? now we retrieve everything
