### ISSUE TITLE
How to mark authors with the same surname (not same authors) in taxon names

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1609]
In the taxonomy of Opiliones we have a few cases of husband and wife, father and son, uncle and nephew who published either together or solo.
It is important and customary to distinguish them.
For example, the couple Benedicto Soares & Helia Soares either published alone, or in duo with Benedicto first OR Helia first.

We want to mark this in the taxon names, for example:

Jim benignus Soares, 1979 > we want this to be Jim benignus H. Soares, 1979

How can we achieve this?

**Comment by mjy** [comment]
You can use the verbatim field to over-ride the display of text, while also keeping the People links there for search purposes.

**Comment by adrik29** [comment]
Verbatim has the great inconvenience that I would be forced to edit taxon by taxon.
I meant how can I mark a given author to ALWAYS appear in a certain way **automatically**?

**Comment by mjy** [comment]
Aha!  You can't.  We'd have to invent some feature as you suggest to say "for all (capital) P people that are authors assign this string to Verbatim (Verbatim is the mechanism we'd use).  

From the broader perspective I personally feel it's better to move towards unified approaches.  While that's not saying what the approach is, it is suggesting that TaxonWorks will "encourage" people to forgo past idiosyncracies so that future meaning is enhanced throughout the field.  Formating people's names seems to be just such a case.  Because we can hyperlink to the person, and ultimately show the full info for that person, we can check quickly in those (very few relatively speaking) edge cases where names are ambiguous between people.

**Comment by adrik29** [comment]
@mjy -- Matt: 

**I fully agree with you in this respect.** 

Yesterday I had a big discussion with one of my dearest mentors, who defends that we should keep the name of the author exactly how it appears in the original source, especially because otherwise "it will be more difficult to locate the reference". I disagree 100%.

I personally made the **unpopular** decision in my catalog to "**retcon**" all names to UNIFY each author. I think that all alternative spellings could even be included in the full info sheet for that person. If you look at my ex-student Osvaldo Villarreal, you may see how his name fluctuated over the years in his publications, same changes introduced by him, others by the publishers.

![image](https://user-images.githubusercontent.com/46284943/86611814-9899e700-bf85-11ea-944f-75a0bb12d335.png)

**Comment by adrik29** [comment]
@mjy = on the other hand, even if I heartily embrace your unified person's names approach,.... Still I would love to see _H. Soares_ instead of plain _Soares_ tagged to the species/genus name.
Maybe it is just as you said, misplaced nostalgia, but for us who work in Opiliones this is important and I would cheer seeing that **implemented in TW**...

**Comment by adrik29** [comment]
@mjy = can you imagine this guy Osvaldo Villarreal calculating his h-index? How much suffering?
