### ISSUE TITLE
ZooBank ID for authors?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1621]
Given the nightmare that is verifying author names, I would suggest that we could have an extra box in the author file for including the permanent ZooBank author ID. Non mandatory, but just for projects who wanted to use it.
For example, I am:
urn:lsid:zoobank.org:author:60FAE1F8-87F7-4A5F-BE78-BEB25BC4F898

**Comment by mjy** [comment]
You're absolutely correct, this is the goal and it's possible now. 

Radial annotator -> Identifiers -> Global.

More imporant yet we should add ORCiD to people as well.  Thankfully you can stack as many identifiers as you want on a person, we're identifier agnostic, the more the merrier.

**Comment by adrik29** [comment]
@mjy -- Hello, Matt, I was thinking first of ZooBank because dead people usually don't have neither ORCID nor Research Gate, nor Web of Science ResearcherID.
But, as you said, the best thing is to be able to add all of them if you wish.

**Comment by mjy** [comment]
Ping @dshorthouse.  Comments on deceased issue? 

@adrik29 note https://bionomia.net/ that links people to specimens, same concept, David's project.  We want to share/use their API to enrich our data ultimately.  They have links to wikidata as well.

@jrflood is adding the People endpoints to the public API as he gets a feel for them, it's his current task.

**Comment by adrik29** [comment]
@mjy -- thanks for the reference to **Bionomia**, of which I was unaware. I think it is a beautiful project! Let's hope it will have great success...

**Comment by adrik29** [comment]
![image](https://user-images.githubusercontent.com/46284943/87857877-764a8680-c900-11ea-91da-dfab4336e316.png)

**Comment by dshorthouse** [comment]
I suppose this boils down to figuring out where is the best place to resolve a name string to a verifiable concept for a person and then secondarily, what services & additional metadata about the person that resolver offers. Although your radial annotator is really cool and you say the more the merrier for stacking identifiers, would/could resolution be better served via wikidata? If you had to, you could maintain a local cache of additional identifiers like ZooBank Author IDs or ORCIDs from a wikidata item (eg https://www.wikidata.org/wiki/Q19966927) just as you could draw-in values for other properties like birth and death dates. And so, instead of making direct use of the radial annotator to do this, you could conceivably direct people to use wikidata and then build the sync functionality from that source.

**Comment by mjy** [comment]
Ping was to address dead people and their lack of ORCiD, sorry for confusion.  Is the take that we just use WikiData as canon, not ORCiD, to address dead folk?

> would/could resolution be better served via WikiData?

Yes and no.

I think all data is conceptualized on a spectrum.  Requiring reference at the far end (GUID) blocks the rest of the spectrum, and from a process/workflow perspective is a non-starter IMO.

I see the stacking of identifiers as the route towards other authoritative sources, while not impeding actual curatorial workflows and needs. By building up internal references through the curatorial process we slowly move people to referencing the same concept. Furthermore, it's more or less also been our philosophy to not believe in mono-sources as a) mono = bad for reasons and b) see a).  This means that from a development philosophy we enable a pluralistic approach to curating data that encourages (sometimes with gentle shoves, e.g. forcing them to share a Person table) curators to consider the best way to link their data to the rest of the world.

Our Person table is a buffer of unvetted and vetted people, it seeks the best of both worlds to serve those who know people, and those who type strings (and see below via UX/leaving the app).

A clear improvement would be to extend our autocomplete to query WikiData for a person when we don't get an internal hit.  A canonical example of autocomplete in this regard would let us implement this very quickly.

> you could conceivably direct people to use wikidata and then build the sync functionality from that source.

Or vice-versa with a bot perhaps.  Accessing and creating People in-line on our forms is too slick for users to leave the system I suspect.  It's tight integration with their existing data (i.e. what is important to them, not others) is also powerful and informative and works for most cases once the datasets gets out of the baby-stages.

Perhaps we could create with a Bot to create on demand- but I suspect Wikidata folks are not going to like the effects of that, i.e. some people just enter people, some seek to resolve, so Wikidata would have many stub pages of identical people- which might not even be possible?

**Comment by mjy** [comment]
> ![image](https://user-images.githubusercontent.com/46284943/87857877-764a8680-c900-11ea-91da-dfab4336e316.png)

Exactly @adrik29!  Now we can expose that via the TW API, and WikiData, Bionomia, etc. can take advantage of your curatorial actions (@dshorthouse  - that were easy to take ;)).

**Comment by dshorthouse** [comment]
> Ping was to address dead people and their lack of ORCiD, sorry for confusion. Is the take that we just use WikiData as canon, not ORCiD, to address dead folk?

Yes, but I'd use the wikidata entity URIs, eg http://www.wikidata.org/entity/Q67331

> I see the stacking of identifiers as the route towards other authoritative sources, while not impeding actual curatorial workflows and needs. By building up internal references through the curatorial process we slowly move people to referencing the same concept. Furthermore, it's more or less also been our philosophy to not believe in mono-sources as a) mono = bad for reasons and b) see a). This means that from a development philosophy we enable a pluralistic approach to curating data that encourages (sometimes with gentle shoves, e.g. forcing them to share a Person table) curators to consider the best way to link their data to the rest of the world.

Fair enough, though it assumes that a bucket of identifiers does not itself incur additional burdens of maintenance. That is, in time, it may be necessary to verify that the identifiers each point to the same concept.
 
> A clear improvement would be to extend our autocomplete to query WikiData for a person when we don't get an internal hit. A canonical example of autocomplete in this regard would let us implement this very quickly. (edit Ping @jlpereira - JS modules for Wiki-Data integration?).

To do that well, it'll be necessary to specify what property(ies) to constrain the autocomplete. You'd otherwise get a heap of spurious hits merely because the labels match. FWIW, these are the properties Bionomia queries against to draw-in entries that minimally also have a year of death (or a year of birth >= 120 years ago):

```
    PEOPLE_PROPERTIES = {
      "IPNI": "P586",
      "Harvard Index of Botanists": "P6264",
      "Entomologists of the World": "P5370",
      "ZooBank Author ID": "P2006",
      "BHL Creator ID": "P4081",
      "Stuttgart Database of Scientific Illustrators ID": "P2349"
    }
```

You're welcome to take advantage of search here should it help: https://bionomia.net/developers

> Perhaps we could create with a Bot to create on demand- but I suspect Wikidata folks are not going to like the effects of that, i.e. some people just enter people, some seek to resolve, so Wikidata would have many stub pages of identical people- which might not even be possible?

Best would be to first query for existence than to bulk create. There are merge facilities in wikidata, but you're correct in that you're likely to get your bot banned :)~

**Comment by adrik29** [comment]
The guys at ZooBank prefer to use UUIDs as true “identifiers”, then embed them within URLs as appropriate to represent resolvable/actionable identifiers, as opposed to Wikidata.
