### ISSUE TITLE
source by project

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1681]
** need to be able to search sources only in project **

need to be able to choose "In project" as 'both' or 'yes' (as in Filter sources page) on the two following pages:
https://sfg.taxonworks.org/sources
https://sfg.taxonworks.org/tasks/sources/hub

Example: search "bionomics of the aphelinidae" - two references are retrieved, one that is in the project with a pdf, and one that is not in the project and has no pdf. There is no way to know which source is part of the project.

It seems that selecting (or better yet having a select and lock) for searches within a project is beneficial.

**Comment by mjy** [comment]
I think in both cases you are referencing the autocomplete interface?

Rather than toggle to only sources in projects, which will ultimately have you adding things you don't need to as, especially as the dataset matures I think the following will work? -

* [ ] clear indication in the autocomplete that the source is in project
* [ ] indicate in the autocomplete that the source has a PDF

**Comment by mjy** [comment]
![Screen Shot 2020-08-28 at 11 35 37 PM](https://user-images.githubusercontent.com/22600/91628682-cd278f00-e987-11ea-84f5-f703c4eb06f9.png)

Supposed to close *this* issue.
