### ISSUE TITLE
Help needed with how to use the "Original combination and classification" section of Edit Taxon Name page

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#1708]
It isn't clear in this section that the user needs to drag the name down to the appropriate taxonomic level in order to activate the fields.  Matt suggested putting a gray box around the taxonomic levels and then putting some instructions to the left of the "set as current" entry telling the user to drag the name down accordingly.

**Comment by mjy** [comment]
Thanks for filing @hhopkins77 

Now I'm waffling, because there *is* help under the "?".  In an effort to keep the interface as clean and not distracting as possible I think we should keep the help phrases there.  This requires more training of users, but it also gets them to learn to use the overlayed help if in doubt.   This is also a case where once learned it's not forgotten.  

So- to keep consistent we'll keep this help phrase out for now.
