### ISSUE TITLE
Original incorrect spelling

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1719]
How do I register this name (which has 3 spellings)? I cannot find the appropriate categories in TW:

Ptychosoma espanoli (Rambla, 1977)

• Scotolemon españoli Rambla 1977a: 272, figs 2a–d. Original **incorrect** spelling, with diacritic.
         Scotolemon espanoli: Rambla & Juberthie 1994: 219. Subsequent **correct** spelling without diacritic (Code Art. 32.5.2.1).
• Ptychosoma espagnoli: Prieto 2008: 51. Unjustified emendation.

**Comment by proceps** [comment]
Three protonyms:
1. Correctly spelled
2. incorrect original spelling + incorrect original spelling relationship (you have to save this name with the proper spelling first; add "incorrect original spelling" relationship; after that you return to the name and add diacritical marks, before the relationship is saved, you cannot add those because it would not validate the name string.
3. third protonym with the relationship "unjustified emendation" pointing to the first name

All those relationships are available when you open complete list of the ralationships.

After you got all 3 in place, in addition you can put a citation to the number one to reference the paper where the name was corrected.
![image](https://user-images.githubusercontent.com/5597748/92416448-24b1c180-f123-11ea-9f30-1ccb4cfc7ffe.png)

**Comment by adrik29** [comment]
Thanks, Dmitry, I will try to get those in place...
