### ISSUE TITLE
Syncronize (or remove?) `docker-compose.yml` to reflect newer database versions/containers.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1847]
See `mdillon/postgis:10`

**Comment by LocoDelAssembly** [comment]
Not sure why this doesn't show up in git history. I actually migrated to postgres12, but then reverted because I change like that could make existing volumes unusable, so only client is upgraded.

If you mean just using https://hub.docker.com/u/postgis repo instead of mdillon, I think there was some subtlety that did not make them 100% equivalent.

**Comment by debpaul** [comment]
@mjy @LocoDelAssembly status of this?

**Comment by LocoDelAssembly** [comment]
https://github.com/SpeciesFileGroup/taxonworks/commit/8695ffd504a1ae549a1ed7cf203c1e80664fd3b8 solves this problem by providing automatic data migration. Also there is an explanation at https://github.com/SpeciesFileGroup/install_taxonworks/tree/master/development/docker#fatal-database-files-are-incompatible-with-server if the migration process doesn't work.
