### ISSUE TITLE
DWCA importer feedback - import fails with large datasets

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#1903]
**Describe the bug**

Not sure the best way to provide feedback based on my two tests of the DwCA importer in sandworm. Here are the issues I encountered.

**To Reproduce**
1. I logged into SCAN and clicked the "Live Data Download: DwC-Archive File" link. At the time we had >134k records
2. Then I logged into sandworm and clicked on the Darwin Core import task
3. I dragged the PSUC-ENTO_DwC-A.zip into the box
4. TaxonWorks whirred for a bit. The end result was:

<img width="335" alt="Screen Shot 2020-11-19 at 11 17 26 AM" src="https://user-images.githubusercontent.com/8043009/99692978-e0af3700-2a58-11eb-90df-58872920d3e5.png">

It's not clear why >10k were "errored" nor why 1 failed nor why only 2,693 records were imported. The >119k records that were "ready" never imported. The app seemed stalled, with no changes overnight after it got to these numbers.

A second attempt with the same dataset, in another project, failed to upload at all. All records were labeled "not ready" and clicking "start import" results in no action.

<img width="1314" alt="Screen Shot 2020-11-19 at 11 57 01 AM" src="https://user-images.githubusercontent.com/8043009/99698175-78fbea80-2a5e-11eb-88ce-1b4426cb69d2.png">

**Expected behavior**
I expected the records to import successfully and for any errors or failures to be explained. Duplicated catalog numbers? Missing some key data that are required in TaxonWorks?

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***

- Sandbox - sandworm

- Chrome Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by LocoDelAssembly** [comment]
@adeans If you click on 'Errored' you will get details about the problem. Examples:

![image](https://user-images.githubusercontent.com/4991925/99703266-ab651200-2a75-11eb-9478-2b4a406172f1.png)
(In this particular case and many others is because scientificName is blank)

![image](https://user-images.githubusercontent.com/4991925/99703384-d0f21b80-2a75-11eb-9a77-9e54a16f3502.png)
(Because 00 was used instead of leaving unknowns unspecified, you must use YYYY or YYYY-MM format for those, there is previous discussion about this at https://github.com/SpeciesFileGroup/taxonworks/issues/1763, I encourage you to share your thoughts about this aspect there to decide how much we'll relax the checks)

Regarding the other one not NotReady is because mapping catalogNumber namespaces is required before importing (using Settings button):
![image](https://user-images.githubusercontent.com/4991925/99703688-2af2e100-2a76-11eb-9365-b525ad86dfdd.png)
(This one comes from SCAN insects)

Thanks for testing! Will check what is going on with that one that was marked as Failed instead of Errored. This happens when a software error occurred rather than a import data error.

**Comment by mjy** [comment]
@LocoDelAssembly Can we include a link/modal on "not ready" records in the same way that states "* Namespaces are not mapped, see "Settings" or similar?

@adeans given this explanation can we close this issue?

**Comment by LocoDelAssembly** [comment]
@mjy currently this is the modal message when clicking no NotReady:
![image](https://user-images.githubusercontent.com/4991925/103784970-64c57a00-5019-11eb-883c-edca38cca138.png)

Do you mean adding ". Please check settings." to that message?

**Comment by mjy** [comment]
@LocoDelAssembly. Yes, that should work, 'Record can not be imported imported until namespace is set, see "Settings"'

**Comment by LocoDelAssembly** [comment]
Please reopen if something is still unsolved.
