### ISSUE TITLE
Browse nomenclature: do I have to create nominotypical subspecies manually?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1952]
I just moved a species as subspecies below another species. Now it is alone under that species, i.e. without nominotypical subspecies, which is also detected by the Validation:

![grafik](https://user-images.githubusercontent.com/33210201/102366406-614d4e80-3f97-11eb-8c0d-1c5baaf745f3.png)

I cannot find corresponding information in the manuals. Making a genus a subgenus of another genus probably creates an analogous situation.

**Comment by mjy** [comment]
@proceps Please describe, somewhat fully, on NOMENCLATURE_BASICS.  The question also came up with what rank original combination should reference (the sub or original), please reference (it's the sub).

**Comment by proceps** [comment]
TaxonWorks can detect and created the nominotypical subgenus and subspecies automatically when
running Soft validation fixes, but now it could only be done programmatically. Before the fix is
implemented to the interface, it is advisable to created the missing subgenus or subspecies manually.

Soft validation fix is addressed in #207

**Comment by LocoDelAssembly** [comment]
Why is the soft validation placed at the children instead of parent (or both)?

No nominotypical-related errors:
![image](https://user-images.githubusercontent.com/4991925/103775556-f7abe780-500c-11eb-97f5-07102836a74c.png)

Nominotypical error:
![image](https://user-images.githubusercontent.com/4991925/103775587-0397a980-500d-11eb-9056-7a8ded000662.png)

I attempted the programmatic fix with code below, but things stayed the same:
![image](https://user-images.githubusercontent.com/4991925/103778349-e238bc80-5010-11eb-9a10-b58f6cf6213d.png)

However, even if worked, is it desired the nominotypical be created rather than creating a transient homonym genus/species* and use it as parent for the original protonym? That way all data and relationships are dragged with it, including original combination relationships, which would produce the expected result @mjy mentions about the sub being referenced?

*Of course all wrapped in the same transaction that sets up the original protonym as subgenus/subspecies.

**Comment by proceps** [comment]
On my computer. I just created a new subgenus: sg and run the folowing commands:
sg.soft_validate
sg.fix_soft_validations
I have a new nominotypical subgenus is created under the parent genus.
May be not all issues are fixed after the creation. Some could be fixed by running:
new_nominotypical_subgenus.soft_validate
new_nominotypical_subgenus.fix_soft_validations
I am reluctant to move all the species automatically to a newly created subgenus. I believe those should be prevewed and moved manually. The same decision we have when we synonymyze two genera, the editor have to preview all the species before transferring them to a new genus assignement.
Well may be type species could be moved automatically.
Since the fix_soft_validation feature is not implemented in TW, I did not had chanse to explore all possi le solutions.
The warning is present on a newly created subgenus, instead of parent genus, because this is the place where it is most likely you will see it, once a new subgenus is created.

**Comment by mjy** [comment]
@jlpereira and I will be working on the run soft validation fix endpoint
and implementation for TaxonNames as soon as we merge the CE branch.  That
should help us test.

**Comment by MMCigliano** [comment]
I think that the soft validation should also be present at the genus/species level.
it would be great if the soft validation is implemented soon, so we can check if it works properly

**Comment by proceps** [comment]
resolved with soft_validation fix button
