### ISSUE TITLE
DwC-A Workbench - clicking on background during active import stops import

### ISSUE THREAD

**Issue by ChrisGrinter** [SpeciesFileGroup/taxonworks#1957]
**Describe the bug**
Clicking on the background during an active import stops the import. 

**To Reproduce**

1. From DwC-A workbench click Import
2. Then 'start import'
3. And click anywhere on screen
4. Import stops

**Expected behavior**
Clicking the background should not terminate a task, rather the X, Esc, or the "Stop import" button should suffice. It seems very easy to click the background accidentally and stop a process you intended to leave running.

Could clicking the background minimize the task while keeping it running? Or can we have a minimize option?

**Screenshots**
<img width="970" alt="Screen Shot 2020-12-21 at 3 42 02 PM" src="https://user-images.githubusercontent.com/68249867/102832395-14a4b180-43a3-11eb-9e8c-e2249a7bb9e2.png">

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandbox - <GRINTER_casent_5aug2020>
- Browser [Firefox]

**Comment by LocoDelAssembly** [comment]
Thanks @ChrisGrinter for testing!

> Could clicking the background minimize the task while keeping it running? Or can we have a minimize option?
At present the way to make it keep working while doing other stuff in TW is to open another tab in your browser. In the future I might change the way the processing is done in such a way that if you abandon the page completely the server keeps importing regardless. Delaying this mechanism for a bit now since it is harder to debug.

@jlpereira can closing the import by clicking outside the modal be prevented when import is in progress (or just disable it altogether and keep `×` as the only way to close)?
