### ISSUE TITLE
Task - Import Nexus file

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2029]
As a curator I want to import Nexus formatted files.

Supported by:
* gem https://github.com/mjy/nexus_parser.
* existing approach https://github.com/mx3/mx/blob/e63b72db1e3cfd3f448430fc2bc07214288ab925/app/models/dataset.rb

**Comment by mjy** [comment]
To start we need to modernize the gem, completing the issues at https://github.com/mjy/nexus_parser/issues.

**Comment by mjy** [comment]
Screenshot of the mx import preview: 
 

<img width="1212" alt="Screenshot 2024-03-26 at 9 38 59 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/2c23be92-17ef-44b7-b1f5-b9ef5d183b97">

**Comment by kleintom** [comment]
Do you have any thoughts on how to handle `gap` states in TW? Using the standard gap symbol `-`, nexus_parser would import a gap state as having `label = '-'` and `name = ''`. As far as I can tell mx allows character states to have blank names (but not state labels). TW requires character states to have both non-blank name and label, so I'm not sure how to import them at the moment.



> * Some way, maybe very simple on the ObservationMatrix, of tracking how the import is going

I haven't thought a lot about this, but an approach along the lines of https://github.com/d4be4st/progress_job (now defunct) - adding a column on ObservationMatrix that gives a percent progress - seems like it would work, does that sound reasonable?

**Comment by mjy** [comment]
Re gap- In TW add a CharacterState with `name` 'gap' and `label` '-'.

In general we don't want to add columns to an IsData model that aren't attribute related, i.e. columns should describe the instance of the thing.  There are some exceptions of course, but we want to keep "function" as isolated from "form" as possible, just as a design guideline.

All this to say I too am unsure, perhaps we don't really need it if we have a robust "all-in-one" with fallbacks (transactions?) + delayed job.  The alternative is something like the DwC importer we have, where we can go row-by-row and see where individual rows fail, and why.  In this case the data are staged in new tables.  Might be over-kill (the mx version was easily functional enough).

Making use of this at some point has been of interest- https://guides.rubyonrails.org/action_cable_overview.html

**Comment by kleintom** [comment]
Another new person question:
It was making me a little sad thinking about creating 1,000 otus (or descriptors or whatever) one db call at a time in succession, so I started rewriting to array-create everywhere I could, and then it occurred to me that I needed to worry about timeouts and noticed all (or most?) of the existing controller `batch_create`s do just create one object at a time. If it's appropriate to discuss here, can you say a little about why that is?  Is it even worth worrying about for 1,000 creates? I'm fine with keeping as is - one at a time - for now in any case. 
(I do notice there's a new `QueryBatchRequest` for doing updates in batches. I would have no feel for appropriate caps, which is kind of the issue here.)
Related question: I assume it's safer to do large queries, like querying for 1,000 items at once instead of one at a time would be fine and a useful thing to do? Thanks

**Comment by mjy** [comment]
@kleintom In brief the primary reason we create one at a time to 1) invoke the model-based validation and and 2) cascading calculation of `cached` fields or other indecies.  This definltely comes at a cost.  for the most part we have made the decision to sacrific speed for quality.   

We have felt safe with this approach largely because we assume that the vast majority of curation happens on individual records, rather than the bursts of "batch" style. If in the future we find this balance to shift signficantly we will definitely, as you note, have to reconsider the life-cycle of the process.

We also assume that users are in the system for the long-term and willing to sacrifice "initialization" time for the ability to operate on their data in novel ways.  This is also an assumption that we need to keep checking.

**Comment by mjy** [comment]
I should also note that vast majority of matrices will be much much smaller than 1k on either dimension, perhaps more like 100x50, or less.
