### ISSUE TITLE
Subfamily ending names are being detected as `supersubfamily` classification

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2194]
@tmcelrath - steps to replicate

**Comment by tmcelrath** [comment]
Basically, just create a name ending in "-inae", assign a parent that is a family ending in "idea", and the suggested rank is "supersubfamily" instead of "subfamily"
![image](https://user-images.githubusercontent.com/11411328/115611220-6a388e80-a2af-11eb-9cb0-a67aed48ad5d.png)

Also, an issue when importing DWC: names automatically created that should be subfamilies are supersubfamilies:
![image](https://user-images.githubusercontent.com/11411328/115611465-baafec00-a2af-11eb-90a4-4ced6b9d0224.png)

**Comment by LocoDelAssembly** [comment]
DwC importer uses same algorithm to guess ranks for names listed inside `higherClassification` (with additional aiding form names placed in rank fields and scientificName parsing).

**Comment by proceps** [comment]
fixed in soft_validation branch
