### ISSUE TITLE
Recent Updates via API

### ISSUE THREAD

**Issue by jcabbott13** [SpeciesFileGroup/taxonworks#2207]
Is there a way to call recent updates to a project via an API call?

**Comment by mjy** [comment]
@LocoDelAssembly this is another service route.

Perhaps `/api/v1/activity/` as the base?

**Comment by LocoDelAssembly** [comment]
What the output should be like?

Was about to suggest `/api/v1/project/:id/activity` but with present API route structure looks `/api/v1/activity/` is the correct one.

**Comment by mjy** [comment]
We can get project with `project_token` (and/or maybe `project_id`), and other params from the housekeeping filter concern.

Output should be unified with the stats type approach at this point, it's essentially a count for now.  

At some point we need to choose a framework to (optionally?) format responses in (e.g. JSON-LD) so that we provide status etc. consistently.
