### ISSUE TITLE
Browse OTU: assign image to collection object

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#2287]
How do I connect a photo to a specimen? For example, one species has a series of 8 photos of the holotype (in OSF was missing the connection between photos and specimen). This seems possible, but not straightforward. In this case it would be nice to be able to select all 8 photos and connect them to the holotype in one go.

**Comment by mjy** [comment]
There are multiple ways to do this:
* Use a radial annotator in the context of the CollectionObject and click on the depictions slice.
* Use the comprehensive collection object task and drag drop the images to the specimen
* Use the new type task and drag drop the images to the specimen
* Use the new image task and drop all the images, choose the collection object, and apply them as depicitons

**Comment by typophyllum** [comment]
Thanks. The depiction slice doesn't show the corresponding images. It is still unclear to me how to proceed, when I am in Browse OTU and detect* that the photos are not connected. How can I access from the specimen side the images that are in scope of the corresponding species/the same OTU?

*) This is also not straightforward. I have to open one of the photos to see the text saying it belongs to the holotype, and also open the holotype section to see that the images are missing there.

**Comment by mjy** [comment]
I suspect you opened the radial annotator for the OTU (see the class of object on the popup form on the top right) rather than  a specimen?

You would have to navigate to the specimen in question to add the image, I don't think we will have the capacity to drop radial annotators on every specimen reference on that page (it's mean to be read only rather than).

But!  There are hot keys.  See picture.   I suspect we should also add a navigation option off of Browse OTU to cover things that are common.  

<img width="1338" alt="Screen Shot 2021-06-02 at 5 25 12 PM" src="https://user-images.githubusercontent.com/22600/120560004-a2131580-c3c7-11eb-964e-b2695371c56e.png">

**Comment by jlpereira** [comment]
@mjy I already discussed this with Holger at the meeting and showed them how to achieve it. It is already solved. Closing
