### ISSUE TITLE
Annotator wheel is far from the button to open it

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2351]
After clicking on the annotator wheel, I need to drag my mouse across the screen to interact with it.

Could it open closer to the button, or could there be a shortcut to open the wheel?

![image](https://user-images.githubusercontent.com/33206210/126051231-eb291134-5dc4-4e67-ae11-341812c47836.png)

**Comment by proceps** [comment]
When you click on a particular sector, the information from that sector is opens right to the wheel, taking most of the screen space. There should be some keyboard shortcuts to navigate to individual sectors.

**Comment by mjy** [comment]
This issue is about placement of the modal form, i.e. what happens afterward a click on the annotator.  While we agree that moving the mouse some distance is not optimal, the alternative is worse. We thought long and hard about how to do this, and it follows best practices:

* the annotator is a modal, the user must deal with it before they do anything else
* the annotator is always opened in the same place, so that the user doesn't have to look around the screen when clicked
* the annotator is centered in the screen, so that it' prominent in the users view
* the annotator opens a series of forms of various sizes and forms, opening those forms directly beside the annotator will force us to use all sorts of contortions to fit the form in tight spaces, along borders of the screen, etc., this would lead to the user having to find form elements in different places (styled into different places) depending on where the annotator was placed, leading to confusion

I'm going to close this in favour of specific issues that reference hotkeys to opening the annotator (or other modals) or new code directly referencing open specific slices or opening the radial to specific records (as we discussed in the meeting).
