### ISSUE TITLE
Task - Filter Sources - download bibtex

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2374]
![image](https://user-images.githubusercontent.com/5597748/127357165-18cc0868-3ffc-4694-8e8c-461306dac9c2.png)
There were several problems reported with BibTex export. 
<strike> 1. Do not include year suffix, most of the Bibtex programs do not recognize it on import. </strike> Dupe of https://github.com/SpeciesFileGroup/taxonworks/issues/1943
2. remove white spaces before the field names, BibTex program do not recognize the fields on import if there is white space before it.

**Comment by debpaul** [comment]
@proceps is this still an issue? What BibTex program doesn't recognize the formatting when it includes the indents?

**Comment by debpaul** [comment]
- @proceps are these sources in your Project? 
  - (If I'm not already included, could you add me?)
- Can you please include a test set of bibtex entries for testing?
- Maybe? other issues. I see a - (dash) between the pages that looks like -- instead of -
  - `  pages = {731–734} ` compare to `pages = {731-734}`
- (Maybe not related. I note that underscores, if present inside certain values, will cause bibtex import to standard programs to fail, see https://latex.org/forum/viewtopic.php?t=11280)

**Comment by proceps** [comment]
@debpaul I do not use bibtex for import or export. I do not remember details. The issue was reported by somebody during our weekly meeting. We may close the issue before we get more specific comments on the subject.

**Comment by debpaul** [comment]
See also ticket #2719
