### ISSUE TITLE
Names showing in hierarchy not direct subordinates

### ISSUE THREAD

**Issue by mikemaehr** [SpeciesFileGroup/taxonworks#243]
When browsing nomenclature, the hierarchy at the left shows non-direct subordinates. The problem seems to be with names (taxa) that are considered to be synonyms. In the abstract, what is showing up is not direct children, but "grandchildren" - not names that have been synonymized directly below the parent but those synonymized below the child of the valid taxon, essentially being pushed up a rank. A specific case may help clarify this, although this could be related to the import.

In Plecotpera (using sandbox and SF data), the suborder Antarctoperlaria (parent Plecoptera) has one synonym, (Gondwanoperlaria), and two superfamilies (Eustenoidea and Gripopterygoidea) directly below it. Each of the two superfamilies has a single synonym Archiperlaria and Leptoperloidea respectively. In the hierarchy, Gondwanoperlaria shows up under Plecoptera, while Archiperlaria and Leptoperloidea show up under Antarctoperlaria.

Link to Antarctoperlaria in SF: http://plecoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1152783

Link to Antarctoperlaria in TW: http://sandbox.speciesfile.org/tasks/nomenclature/browse/1149090

**Comment by mjy** [comment]
@mikemaehr Do you mean what you are seeing here?: 
<img width="256" alt="screen shot 2017-09-25 at 4 41 18 pm" src="https://user-images.githubusercontent.com/22600/30832361-730c957c-a210-11e7-9658-0bb78a1d09a8.png">
<img width="264" alt="screen shot 2017-09-25 at 4 41 23 pm" src="https://user-images.githubusercontent.com/22600/30832364-7530173e-a210-11e7-93a5-ffeb4a59c8fb.png">
<img width="257" alt="screen shot 2017-09-25 at 4 41 28 pm" src="https://user-images.githubusercontent.com/22600/30832367-77affed4-a210-11e7-9438-91f075494e7a.png">

If so then the issue is that parent hood in the hierarchy in TaxonWorks does not imply synonymy but rather where we would expect to see the name if we knew nothing else about it.  The parent in the classification of all the names is the same in TaxonWorks model, the synonym is asserted separately.  The invalid/valid/both buttons help to express this.  We can add other navigations/views that express indentation as you'd see in Species Files, however it's important for TW users to understand how parenthood is used, and that its different than in SFs, so its likely better to get a feel for this pattern.

**Comment by mikemaehr** [comment]
Yes. I was thinking m
ore in terms of not just SF but all published classifications, where parent-child relationships are more or less intuitive.

**Comment by mjy** [comment]
Perhaps its better to think of that navigation aid as the index at the back of those publications.  Those indexes list names alphabetically by rank, just like you see here.

**Comment by mikemaehr** [comment]
Ok that makes sense but where do we find an actual classification that might me found within the body of a publication? Is that going to be found using OTU's and as that UI gets developed?

**Comment by mjy** [comment]
Good question.  What you see is actually a single taxonomic history in part of that larger catalog (obviously).  Right now we have most of the flexibility required to bounce between nomenclature in the browse-nomenclature interface, so in essence the function of a nomenclatural catalog is done, i.e. its an actual publication but in a modern format.

For example you can quickly determine the validity of a given name via various navigation routes.  You can also quickly see all the valid names under a given taxon (nav on the left in combination with buttons).  The asserted (actual(?)) hierarchy is visible in the bread crumbs on top, etc.

In thinking about this I'm wondering if we should identify the *very* specific things you'd want to do.
