### ISSUE TITLE
[Bug]: DWC-A Workbench import: failed data is blank when clicking failed.

### ISSUE THREAD

**Issue by MJTPaleo** [SpeciesFileGroup/taxonworks#2808]
### Steps to reproduce the bug

```bash
1.Put data into DWC-A Workbench for import
2.Select appropriate namespace
3.Click import on any line of data. The data will fail. Failure link is blank (giving no reason for the error).
...
```

### Expected behavior

It should give me a specific reason for the failure (or at least the first failure even though there may be more than one)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

workbench

### Version

SANDBOX - build f81a9e4ea on 2022-02-09T17:36:30Z

### Browser Used

Firefox

**Comment by mjy** [comment]
@LocoDelAssembly is this resolved now?  If not likely needs more input.

**Comment by LocoDelAssembly** [comment]
I guess this is related to the error that was fixed in latest released version. It is OK that Failed shows nothing, that is private and has to be inspected with rails console.

Problem in question probably was https://github.com/SpeciesFileGroup/taxonworks/commit/cc13fc026a7b3c057e6a1a89731cf8b9b3353824
