### ISSUE TITLE
[Bug]: Matrix row coder search bar searches for some local ID instead of OTU name

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2902]
### Steps to reproduce the bug

```bash
The search bar in the matrix row coder seems to only search for some internal ID string, instead of actual OTU names.
```

### Screenshot

![searchbar](https://user-images.githubusercontent.com/70152690/163180171-bd0b6664-12f6-4835-8269-59645e07088c.jpg)

### Expected behavior

Expect to be able to search by actual OTU string. 

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Browser Used

chrome

**Comment by LocoDelAssembly** [comment]
Maybe @proceps can comment, but looks deliberate:
```ruby
    return observation_matrix_row.name unless observation_matrix_row.name.blank?
    o = observation_matrix_row.observation_object
    s = label_for(o) 
    s.gsub!(/[^\w]/, '_')
    s[0..11] + "_#{o.id}"
```

Since the rows have no name set (checked with `ObservationMatrixRow.where.not(name: nil).count` and count is zero), then the synthetic names are always used.

A display change might have been introduced 2 months ago: https://github.com/SpeciesFileGroup/taxonworks/commit/9a7d52b7f70fc97a95c0d0ddcb144523ddf0331b
