### ISSUE TITLE
[Bug]: Wrong Catalog Numbers put in DWCA Export "otherCatalogNumbers"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2945]
### Steps to reproduce the bug

```bash
1. When I add a second catalog number to a specimen
2. Then I check the "otherCatalogNumbers" DWCA export field in Browse CO
3. then I see the same two catalog numbers in "catalogNumber" and "otherCatalogNumbers"

e.g. https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=957150
```

### Screenshot

Identifiers pane:
![image](https://user-images.githubusercontent.com/11411328/165149632-301b2db2-d8c6-4614-bb33-edcfda977808.png)

DWCA fields:
![image](https://user-images.githubusercontent.com/11411328/165149576-7839a3a5-0576-48b8-9900-76d8751b2f84.png)

### Expected behavior

Should export "non-primary" catalog numbers

### Environment

Production

### Version

0.24.2

### Browser Used

Chrome

**Comment by LocoDelAssembly** [comment]
Fixed in https://github.com/SpeciesFileGroup/taxonworks/commit/830d73e0d4a767579d5d6ad85def1e27abcdc25c (or subsequent commit likely)

When looking in production copy I have I do not even get `otherCatalogNumbers` in browse collection object unless I add an additional catalog number:

![image](https://user-images.githubusercontent.com/4991925/165152025-bfee0abc-d99b-43c1-9645-5de73d53e291.png)

Deleting the test catalog number shows once again only `catalogNumber`

![image](https://user-images.githubusercontent.com/4991925/165152354-ce9888cd-ff96-4f88-acc5-832c3de5f358.png)
