### ISSUE TITLE
New task - New container

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3038]
New task needed to manage storage containers (specimens in boxes, boxes in cabinets, cabiments in rooms, etc.) We already have a model to handle this data. At the moment, this is getting as a priority.
We also have a related outstanding issue #1058, #68 for collection profiles.

**Comment by mjy** [comment]
For this task start with a  focus on single containers, as opposed to "Task - container layouts" where we arrange many.  Ultimately maybe we merge both concepts.

_In practice we might not use this much, as we'll likely invoke code to clone or create from existing containers once they are spun up._

Container properties:

Required:
* [ ] type (requires new `containers/container_types.json`)
   * [ ] some container types have fixed sizes (e.g. 96 well plates), we'll have to provide that in `container_types.json`, others don't 
* [ ] x,y,z size

Optional:
* [ ] name 
* [ ] parent (optional, another container that can legally contain this container)
* [ ] identifiers

Consider adding attributes
* [ ] repository (though buildings themsleves are containers that can be repositories, so that hierarchy may be preferred), either way we need some relationship at some point to Repository
* [ ] css (style preference for visualizing, like color)

**Comment by mjy** [comment]
Functionally:

*  [ ] Could let user drag out container size, with width/height totals listed at top as they drag (table style)
