### ISSUE TITLE
Data - Collecting Event, List, Displaying collecting events – UI Issues

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3225]
### Feature or enhancement

1. When viewing an individual CE (after double-clicking on an item in the list), the CE attributes are displayed in a long listing that is not ordered by what is most interesting/useful to the user. This requires users to scroll down a long list of attributes (many of which are blank). **Fix:** Develop a visually compact display that shows the most useful attributes and allows a popup box to see the full set of attributes.
2. There are no trip code identifiers shown in the CE list. **Fix:** Add trip code as a column
3. After double clicking on CE, geographic area is taken from the verbatim label, therefore, sometimes abbreviated (see screenshot). **Fix:** use non-abbreviated country name from Data Attributes field
4. The non-abbreviated country name is located in the Data Attributes panel, which seems secondary to the Attributes panel. **Fix:** Incorporate all Data Attributes into the primary Attributes panel for the CE. (see screenshot)

### Location

Data, Collecting Event, List https://sandwich.taxonworks.org/collecting_events/list

### Screenshot, napkin sketch of interface, or conceptual description

![CE attributes](https://user-images.githubusercontent.com/74991451/207121731-eadab6b6-d44f-47cd-ab1e-eb9411050fdb.jpg)

![data attributes CE](https://user-images.githubusercontent.com/74991451/207122400-5186a2c2-d1d3-486e-bb9a-683a54961704.jpg)

**Comment by mjy** [comment]
Thanks for this.

As noted in one of the other issues this is because we confused you with presence the List and Show views, rather than Filter and Browse.  List and show should only be used in specific contexts, mostly for debugging at this point.  The radial navigators, and other navigation should primarily guide through Tasks, not the Show views. 

Our goals should be to get you from Filter, to Browse quickly, then most of these issues are resolved.  

See #3243 for one thing we can do to get folks out of List/Show.

We might have to visually indicates when links take you from one "world" to another perhaps  (e.g. invert the color of the slice if you are heading to Data/List).

A reminder that with DataAttributes we can only display them in context of a list of DataAttributes, not as replacements for standard renderings.  We think that new table-views that include DataAttributes will help put these data side-by-sie with other data in a more effective way.

I'm going to close this as addressed in the Browse collecting event overhaul (#3222) and possibly related to the data import issues in #3224.  Please re-add individual issues with specifics if I missed addressing points here or in the referenced issues.
