### ISSUE TITLE
Task - Geographic Area Lookup: case sensitive geographic areas

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3249]
### Feature or enhancement

Case sensitive entry is required or lookup will not yield results - this places a significant burden on users to know the case sensitivity

@bpescador, @cgrinter, @rich-keller

### Location

Task - Geographic Area Lookup

**Comment by mjy** [comment]
GeographicArea autocompletes, where they are referenced in actual workflows, are far less sensitive and include various other magic.  As referenced this is a tasks that specifically finds exact matches so that their IDs can be transfered to external spreadsheets in preparation for downstream bulk uploads.
