### ISSUE TITLE
Task - Browse OTUs - OTU results seem arbitrary

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3296]
### Feature or enhancement

When browsing/typing an OTU (in any OTU field throughout TW) the dropdown menu does not display OTUs alphabetically and does not show obvious results. 

For example, typing "_Camponotus al_" for "_albipes_" does not begin to yield the ~16 species of _Camponotus_ that begin with "al". 
The results show morphospecies first as opposed to valid species names first and will include the wrong genus name. See screenshot for whole list of results for "_Camponotus al_".

Fix: drop down menu should yield results alphabetically as each character is typed. If whole genus name is included, do not include other genus names. Similar issue with collector's names discussed in #3231 and #3216 

@bpescador, @chrisgrinter, @rich-keller

### Location

Task - Browse OTUs

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/74991451/215916687-166d87c0-3bf9-4eb7-a4c6-b89fa4d3168e.png)
![image](https://user-images.githubusercontent.com/74991451/215916740-ec4e3b34-420c-4893-a0f4-7dd43df3b1b4.png)

![image](https://user-images.githubusercontent.com/74991451/215917280-1f707a9a-ec71-4465-9ad2-aee2b3e48191.png)

**Comment by proceps** [comment]
For the collector, please use the last name and inicials format. It was tuned very well and and works in most of cases. For the otu name, the name of OTU indead uses the preference. It was done intentionally. I personally more often use Browse nomenclature interface, where the search is optimized by TaxonName. From there you can quickly jump to Browse OTU if needed. As a general rule, if you do not see a result, please keep typing probably one letter for a species name will be enough to find the right taxon. In most cases. a single letter abbreviation for the genus name and few letters for species work for me.

**Comment by AntWeb-org** [comment]
Thanks for the response. 
I am having a very different experience with the results. I expect when I type "_Camponotus_ al" (for _Camponotus albipes_) that the initial results displayed would include all _Camponotus_ species beginning with "al" so I can choose. I get more relevant results typing "_Camponotus_ a" , but still, the species beginning with "a" are not alphabetical and also do not include "_albipes_". The same issue of holds true in Browse nomenclature (see first screenshot for _Camponotus albipes_). Also, if I am entering data directly into TW I would not use the Browse nomenclature feature as it would be an extra step in our workflow.
And still, entering the last name of a collector first does not include all collectors with that last name so I will eventually just need to type in the whole name (see second and third screenshot for Johnson, R.A., and Fisher, B.L. respectively). This makes the dropdown menu somewhat irrelevant. If the dropdown menu was truly alphabetical as one types it would be quicker, visually less cluttered, and have less room for error. Otherwise, it would be quicker and visually less cluttered if I entered names by hand to avoid all incorrect names.

![image](https://user-images.githubusercontent.com/74991451/216111775-5b492193-6df7-4921-a78c-3c076fae06c5.png)
![image](https://user-images.githubusercontent.com/74991451/216111554-47efe613-2ccc-4d42-9507-f7ad8cb1f780.png)
![image](https://user-images.githubusercontent.com/74991451/216111637-6e076ea7-5146-4e47-83bb-6d12a42a5791.png)

**Comment by proceps** [comment]
could you give me the server name and the project?

**Comment by AntWeb-org** [comment]
SANDBOX - build build e002b057b on 2023-02-01T11:13:48Z
and the project name is called Mar Antweb Import

**Comment by proceps** [comment]
I do not see it on sandbox.speciesfile.org, it shold be a different one, could you please copy the address line

**Comment by AntWeb-org** [comment]
https://github.com/SpeciesFileGroup/taxonworks/tree/e002b057b

**Comment by proceps** [comment]
sorry, not github. we have multiple sandbox databases. In the browser address line: sandbox.speciesfile.org; sandstorm.speciesfile.org, sandcastle.speciesfile.org and few more.

**Comment by AntWeb-org** [comment]
https://sandwich.taxonworks.org/hub is the main address
https://sandwich.taxonworks.org/projects/69 is the address when I click on Project

**Comment by proceps** [comment]
Thank you. 
So yes I am looking in browse OTU. Yes, the name is out of search. And even if we sort the list alphabetically, it will be out, because the name has a subgeneric name. It is extremely hard to predict all possible search criteria. Especially for common names like 'alba'. But if in browse OTU I search "Cam albip" I get a single name. I just need to find a unique combination for the name. And keep typing before I get a result. In my experience, abbreviated genus name and more complete species name works better. In your list, you can see that each name has 'al' inside. What happens, I do not always have a correct spelling of the name lets say, the the name is 'albonotata' and the name is spelled as 'albinotata' in the paper. I have to do partial search to find it. To make it more complicated, I do not know what is misspelled, the genus or species epithet. I have to do partial search. An partial search do not always start with initial letter. Actively editing the DB of Auchenorrhyncha for several years, I found that the search interfaces are very efficient in TW, although, there are some marginal cases which are more difficult to find than the others. 
Same for the authors. "Fisher" is so many Fisher in the DB, that if I simply alphabetize by the string, you will get "Fisher" without initials at the top of the list. The author list is optimized by the number of uses in the database. It is not always intuitive. But it is very efficient. If I need to search for "Dmitriev, Dmitry Alexandrovich" I will make a search for "Dmitriev, D.A." and will get a result, and again, all depends how common the name is. Dmitriev is not a common last name, I will get it with partial search, but with Fisher, adding one letter of initial returns your more precise list. In some extreme cases, more than one letter is needed. Please remember, that all authors are shared across the projects. We have almost 150.000 people already recorded across all projects. The search also prioritize the people previously used in the existing project. Sandboxes also has a lot of duplicates. The situation is little bit better in the production database.
![image](https://user-images.githubusercontent.com/5597748/216156045-30188ea0-c53f-4a6b-89ec-a9e5b74cf80d.png)

**Comment by mjy** [comment]
Closing as out of date.  We've iterated on autocompletes in other issues, and they will certainly evolve, but the collective seems to like how they work now.
