### ISSUE TITLE
[Bug]: Filter People task,  Full Name field not working properly

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3394]
### Steps to reproduce the bug

```bash
When I search for C. Hugh Fraser Rowell in the Filter People task, by entering the complete name in the *Full Name* field, I don't get any results.
If I complete the *Full Name* field only with: Rowell, then I do get results.
I have tried many alternatives for completing that field and also putting only "C. Hugh" in the *First name* field... but I do not get results.
The only ways it works is when I use the complete first name in the *First Name* field and only the last name in the *Full Name* field.
```

### Screenshot

![image](https://user-images.githubusercontent.com/63611746/235754084-f7ebdf9f-504c-48f4-9c63-3f3def71b439.png)
![image](https://user-images.githubusercontent.com/63611746/235754160-e004d38e-a345-440b-8167-560a12c9e158.png)
![image](https://user-images.githubusercontent.com/63611746/235754221-a872f3dd-063c-452d-be17-764779797f20.png)
![image](https://user-images.githubusercontent.com/63611746/235754391-b66ec24c-f3da-4551-b48f-68fb79da0d2c.png)

### Expected behavior

I expect to get results when using any part of the name combined, such as Hugh Rowell, in the *Full Name* field. 
Specially when working with certain names in which it is not easy for me to distinguish between the first name and the last name.

### Additional Screenshots

SANDBOX - build [8f41d3fc8](https://github.com/SpeciesFileGroup/taxonworks/tree/8f41d3fc8) on 2023-05-02T14:53:23Z [Issues](https://github.com/SpeciesFileGroup/taxonworks/issues)

### Environment

Sandbox

### Sandbox Used

sandcastle

### Version

build 8f41d3fc8 on 2023-05-02T14:53:23Z

### Browser Used

chrome

**Comment by proceps** [comment]
General search pattern for people is "Last name, First name" or "Last name, Initiales"

**Comment by mabecabrera** [comment]
![image](https://user-images.githubusercontent.com/63611746/235756573-bc501f42-bca9-4e7f-93f4-9b8a399ef1e2.png)
![image](https://user-images.githubusercontent.com/63611746/235756705-4a413860-7a7a-42d2-a792-8366b3ea7312.png)

What happens if I don't know where to put the comma? Such as in: RODZAY BIN HAJI ABDUL WAHAB

**Comment by proceps** [comment]
Well, you will need to play. With such complete name, it is usually not a problem. Coma is optional. You can always do partial search. In this particular case, I would try "Wahab, R.B.", I am confident, that I would get a result. It is just experiment. I am using people search for several years, and it is very rare when I cannot find the name from the first attempt. The most complicated cases are diacritical marks, in such cases, I would try to avoid those if the name is long enough for example for Stål, Carl, I will search for "St l, C."

**Comment by proceps** [comment]
you example is quite unique. Search just for "Wahab" returns a single record in the database, you do not even need initials. "Rodzay" do not return anything. Like any search filters, you need to think the most unique part of the name. For the species name, if I search for "alba" I expect to see hundreds of the results. If I search for "R. alba" I will restrict the search to genera which start with R.. If I search for "Ro. alba" I will restrict it even more. For "cockcrofti" iI do not need generic name, since I have only a single species epithet like this in the database. The same with the authors, You need to find a unique combination. Often it could be abbreviated. For example I will search "Ossian" for Ossiannilsson, not even initials, because the last name is so unique, but you definitely need initials or first name if you search for "Zhang"

**Comment by proceps** [comment]
Actually, I prefer searching by initials. It does not need to be a first Initial, it could be a second initial, as long as combination is unique. There are a lot of people already in the DB, and for many, I do not have have full name spelled. If I find a person with initials only, and I know it is the same person. I will go to editing, and update the first and last name, if I have those. This will make my search easier next time. If I have very short last name with diacritical marks, which could be difficult to find, I will add an alternative spelling of the name without diacritics, to make my next search easier. If alternative spelling is available, it is also used for matching.

**Comment by proceps** [comment]
The general order is the same how TW represents the data. See an example below. 
So you can search for "Linnaeus, Carolus", "Linnaeus, C.", "Linna C", "Lin Car", "nnaeus lus", and in all cases you should get the result.

![image](https://user-images.githubusercontent.com/5597748/235765978-6c69c51c-8a37-4ba8-9caf-7be8933dedaf.png)

**Comment by proceps** [comment]
The nice think also, if you enter the name properly, and you did not find the result, you can click "Add new", and the person will automatically created in a proper form for you. I cases of doubt or complicated names (with prefix or suffix) you can use "Expand" button, to manually adjust the name.
![image](https://user-images.githubusercontent.com/5597748/235767761-6cb2f757-4b73-4985-8c6c-5a5949c23b6b.png)

**Comment by mjy** [comment]
@proceps Thanks for the help.  I think we need to consciously start adding this type of help to docs.taxonworks.org and pointing the issue to the documentation added there rather than documenting in the issue and/or we need to consciously sweep through issues tagged with `question` and migrate the help to docs, noting in the comments when that happens.

Ping @debpaul.
