### ISSUE TITLE
[Bug]: taxa distributed in French Guiana are shown to occur in France

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3436]
### Steps to reproduce the bug

```bash
At genus and higher ranks France is erroneously shaded on map as asserted distribution. I guess this is because French Guiana is a French overseas department.

For example genus _Typophyllum_ (_T. trapeziforme_ occurs in French Guiana) and corresponding subfamily Ptrochroziane.
```

### Screenshot

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/e7b2a41f-aca0-421f-951c-028b34f4a153)

### Environment

Sandbox

**Comment by mjy** [comment]
Thanks @typophyllum.  We're aware from a similar issue (Alaska).  We're exploring what the algorithim is doing and what we might do about it.

**Comment by proceps** [comment]
This is actually correct representation of the data. According to GADM, French Guiana is treated at the level of Province for France. The same as Hawaii is a state of USA. So yes, if we display the distribution of the country level, France will be shaded if the species is distributed in French Guiana, or USA will be shaded if the species is only known from Hawaii. It also works wise versa. You can see on the map that Galapagos is shaded, probably because the species is reported from Ecuador.

**Comment by proceps** [comment]
The only way to avoid it would be to show the distribution on the state level, not sure if this will solve all problems or not.

**Comment by mjy** [comment]
We already work at state and country level, but there are cases where things get fuzzy (spatial overlap) so we have to tease out what is happening.

**Comment by typophyllum** [comment]
Couldn't the TDWG levels be used, or someting else that depends on geography and not on rather arbitrary political boundaries? Currently all the numerous genera present in France are shown to occur also in French Guiana.

**Comment by proceps** [comment]
Related to #1433

**Comment by mjy** [comment]
Added illustration of the issue at GA level.

<img width="1212" alt="Screenshot 2023-06-08 at 10 22 04 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/e0d95f49-05b5-46d5-a020-74043c8271fe">

**Comment by mjy** [comment]
I believe this is fixed.
