### ISSUE TITLE
[Bug]: "Geolocate" type georeference import ignores uncertainty

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3471]
### Steps to reproduce the bug

```bash
1. When I am in Georeference pane
2. And I use the "Geolocate" pane
3. And I enter two coordinates +uncertainty (<10000)
4. Then nothing is added to uncertainty
```

### Expected behavior

Should be able to properly handle uncertainty on top of coordinates.

### Additional Screenshots

What I'm grabbing:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/1334ccf1-5d0c-4f44-9a4d-d42059b3c006)

What I'm pasting:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/cd8bcae9-f466-429f-8a1f-6baa3433fb0c)

What I get:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/363dc41e-a7db-4c39-9021-5e097da21aad)

### Environment

Production

### Version

0.33.1

### Browser Used

Chrome

**Comment by mjy** [comment]
The radius is being converted into an error polygon (e.g. a circle that is a polygon) and stored that way.

I have zero recolleciton why we did this.  There are 8.5k records or so that exist in this format. 

I'm going to defer on changing anything other than adding a column to indicate error polygon present until further discussion.

**Comment by tmcelrath** [comment]
Why isn't it just being converted into an error radius uncertainty? That's what I'd suggest as a fix.
