### ISSUE TITLE
Managing placement of many taxa to a new parent

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#3495]
### Feature or enhancement

In the UCD project we are dealing with a lot of changes with family-group names.  For example, recently Cruaud et al (2020) (source 115515) created three new tribes in the Chalcididae subfamily Haltichellinae.  Since each of these have only a few children, they are easy to deal with.  The problem in UCD is that Noyes treated all tribes as synonyms of their parent subfamilies.  Thus, the names and publication details are there, but tribes have no children.

In the Haltichellinae case, we are therefore faced with assigning genera to Haltichellini one by one.  See below, there appear to be well over 100.  It would be extremely helpful if we had a tool to assign batches of these genera to their parents, analogous to the Manage Synonymy tool.  See screen shot below.  The idea is that we would select the genera at left, and then assign the same parent to all of them.

### Location

Task - Filter Nomenclature?

### Screenshot, napkin sketch of interface, or conceptual description

![Screen Shot 2023-07-20 at 8 30 59 AM](https://github.com/SpeciesFileGroup/taxonworks/assets/30122486/40cc6ae0-f0bc-4662-992e-b14fa25cb321)

### Your role

Curator of UCD project in TW

**Comment by rogerburks** [comment]
I have a vision of how a one-stop-shop for taxon names could be handled. It builds from how nomenclatural systems have a number of standard properties built into them. Family group names end in a standardized way. Genus group names must be capitalized. Specific epithets are not capitalized. Additionally, nomenclature has a number of rules that are meant to make name formation objective. We always want to use these properties when they can help us. I have a rule for this:

_If something should be done the same way every time, a computer should be doing it._

something follows from this:

_If we are telling the computer which objectively determined choice we are making, we are doing it wrong. The computer should automatically move forward with the objective determined choice._

This is because computers carry out operations in a far more consistent way than people do. People treat objective decisions in about the same way that they treat subjective decisions, which can lead to errors and bad decisions.

Additionally, we can suggest that data entry has some hoped-for properties: _efficiency_, _accuracy_, and _completeness_. My suggestion aims to improve efficiency and accuracy, and arguably completeness.

- The task should open with a single autocomplete field. You start typing the name into the field. If it autocompletes to the correct choice, you move forward with an edit of it. If it cannot autocomplete, you enter a new name.

- Since names are standardized, the task can attempt to determine information about it. Let us say that it ends in -inae, such as Cleonyminae. The task suggests a few conclusions based on this:
     - This is a name in the ICZN Code
     - This is a family-group name
     - This is a subfamily name
     - Its genitive stem is the part excluding the -inae suffix
- These suggested conclusions should have an option to be overridden, but they would usually be true and they save time if they are true.

- If the name has been found, the option is to edit.
     - The task should automatically place at the top of suggestions two options: elevating one rank, or lowering one rank within the rank group. Let us say that we are elevating its rank. The suggested rank is family, and the spelling Cleonymidae is automatically suggested. Given that this name has appeared in the database before, and that the current parent Pteromalidae is still a family, the task automatically suggests that the name Cleonymidae no longer has the parent taxon Pteromalidae, and now instead has the next-highest parent not of family rank: Chalcidoidea. This is because a valid family cannot have another family as parent. It is always possible that someone is doing things in the wrong order of course, and so this can be overridden. What cannot be overridden is the current valid spelling. The family name is automatically Cleonymidae because this is determined objectively through the ICZN Code. No possibility of typing it wrong: the computer handles it.
     - The task then suggests that all tribes of Cleonyminae be elevated to subfamily rank. These tribes are all listed with options. We override this for all except one: Cleonymini. The task changes nothing at that point, since Cleonymini has no subtribes, and because both Cleonyminae and Cleonymini are Coordinated names.
     - At this stage my concept of `highest_valid_rank` of Cleonym- is used, and it changes from ICZN subfamily to ICZN family. Because of this, Cleonym- is automatically valid at all family group ranks below family. Cleonym- remains not valid at superfamily rank, since Chalcidoidea is its parent, and since `highest_valid_rank` already excludes that possibility.
     - Cleonym- is also automatically `used` at its `highest_valid_rank`, since it makes no sense to elevate a name to a rank and then deprecate its use at that rank. The user of the task does not need to tell the task things like this. It should be automatic. If we see something like this listed wrongly, it is a sign that we entered something incorrectly, which is a wonderful thing to have visible in a task. The logic should also be sequential, so that the origin of an incorrect entry can quickly be found.

Let us say instead that we are decreasing the rank of a family but keeping it as a subfamily. The task knows that a taxon cannot be the same as its parent. Therefore, it automatically suggests that any included subfamilies be treated as tribes. This can be overridden, but when true it saves time.

Now I can suggest some features of the model that should help things tremendously:

- I suggest that the family-group stem is an important part of the model of a family-group name. It can have a property `highest_valid_rank` that controls some aspects of how it is displayed. The child taxa of a family-group name need only be children of the stem. They do not need to be children of the rank, because this is automatic in nearly all cases. The children of Cleonym- are also children of whatever coordinate forms it has. In the case of `incertae sedis` this could be overridden, but this also gives an obvious way to check that `incertae sedis` is properly applied. Any subfamilies of Cleonym- are also valid names, but their `highest_valid_rank` is subfamily. There are no issues with included genera, because generic names cannot elevate into the family group of ranks. If Cleonyminae had a number of subfamilies and no used tribes, genera would have the stem of their subfamily as the parent. If any of these family-group names had a number of tribes, genera would have the stem of their tribe as parent. This constructs a resilient system that makes it easy to perform housekeeping actions with them later. If we designate that there are multiple valid subfamilies in Cleonymidae, then Cleonyminae is automatically switched to `used`. Otherwise, if Cleonymidae has only one valid subfamily (Cleonyminae) then that subfamily is automatically switched to `unused` if it happens to exist in the database.

- For subgenera and subspecies, the `highest_valid_rank` can be used to disambiguate their rank. The nominotypical subgenus has a `highest_valid_rank` of genus, but is automatically valid at all genus group ranks. The parent of species will be the generic name, and it does not break, no matter if we use the subgenus coordinated name or not. If the subgenus coordinated form is not used, then the scientific name does not display it. Any other subgenera have a `highest_valid_rank` of subgenus. This should also make housekeeping much easier when genera and subgenera change rank. There should be no issues, since the scientific name is formed through an objective process, and again takes into account the field `used` when determining if a subgenus or subspecies name is displayed.

These should construct a completely solid and logically consistent system that will make nomenclatural housekeeping relatively easy.

**Comment by JimWoolley** [comment]
Roger,

Thanks for this complete description of you ideas for managing familiy names.  It would indeed save some time, and perhaps some errors.

However, from my point of view the problem is not creation of correct protonyms for family group names for categorical levels that do not currently exist in TW.  In fact, in the UCD, most of them are already there at one or more categorical levels, and if not, they can easity be cloned to retain authorship, source publication, type genus, etc.

The issue that I brought up was the necessity to link each child to a parent individually, if the links do not currently exist.  In UCD, this problem occurs if tribes have been used in the literature.  Since all tribes are treated as synonyms of their nominate subfamilies, all the genera are treated as children of the subfamily.

I don’t know if you proposal solves that problem, I will leave it to the grey-beards to comment.

Thanks,

Jim


Jim Woolley
Professor Emeritus
Department of Entomology
Heep Center MS 2475
Texas A&M University
College Station, TX 77843-2475

**Comment by rogerburks** [comment]
At least from my perspective I think it does help at least. Since all coordinate forms have the same type (genus in the case of family-group names), they would all be automatically linked. Location of non-types could be done using the table that you suggest, although it would also likely be rapid enough through assigning parent family-group stems as well—autocompletes work with taxon ID numbers by the way, which is probably the fastest and most failsafe way to use them.

**Comment by mjy** [comment]
Duplicated as #3584.
