### ISSUE TITLE
Identifier::Global add soft validation for resolves?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#352]
* Add instance method `resolves?`
* `resolves?` should check that identifier starts with http(s):// before using another method that actually calls the URL
* "another method" should likely get the header but not the body, sensu https://stackoverflow.com/questions/17454956/how-to-get-http-headers-before-downloading-with-rubys-openuri
* add `sv_resolves?` asv_resolves?` as a soft validation

**Comment by LocoDelAssembly** [comment]
As presently implemented `Identifier::Global` resolvability soft validation assumes HTTP(S).

Soft validation should be moved to `Identifier::Global::Uri` maybe? Perhaps even better if `Identifier::Global::Uri:Http` or something that denotes it is an HTTP(S) identifier. However if UI asks type rather than be autodetected on create/update then perhaps besides moving also disable check if it is not a HTTP(S) URI.

@mjy
