### ISSUE TITLE
Include link to local PDF in Source list.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#363]
When I browse the source list, and there is Documentation for the source, then I can access (download) that source directly from the list.

**Comment by JohnHeraty** [comment]
**workflow to display pdf in sidebar**: go to Browse Source: <find> reference: <select reference>…. click pin up in upper right to red, then click on half-hidden green pin on right side of panel, when reference is visible, click the ‘hamburger- (three vertical stripes), and select pdf, then modify to fit in window. 

**Suggestion**: automate the above workflow so that it is a single step attached to the reference whenever it is displayed (i.e. in the root page; add a pdf icon when available). i.e. double click a pdf icon and it automatically gets pulled up on the right until closed.

**Comment by mjy** [comment]
Awesome @JohnHeraty, thanks for using the issues list, and welcome!  You can preview what your message looks like with 'Preview'. Often we blocks of triple "```" to let us not wrap comments.

**Comment by mjy** [comment]
@JohnHeraty Made your suggestion a new one - https://github.com/SpeciesFileGroup/taxonworks/issues/368.  This issue will remain for one-click download (as opposed to visualize).
