### ISSUE TITLE
Improve semantics on CollectingEvent identifiers with respect to DwC import

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3800]
Thanks to @debpaul's testing we have some things that we should work to improve on.   The basic issues are included in the image below.  

@LordFlashmeow, @LocoDelAssembly please chime in after digesting this.  In particular we need to re-vist how AntWeb is getting data in-out, as they have most extensively imported identifiers.

I do anticipate a couple things:

* Clarifying the concept of Identifier::Local::TripCode to more closely align with `fieldNumber`.
* Perhaps supporting namespacing of fieldNumber based imports
* Perhaps using `fieldNumber` as a ways to collate unique CEs, as we do for `eventID` (we'd have to prioritize what to use if both present- something like use `eventID` for uniquness and add multple TripCode identifiers
* Ensure, where intended, that the dwc export aligns, it's crossing concepts right now I think.
* Potentially migrate some existing data to clarify evolved semantics (e.g. change Identify types, etc.)

In general we also need to interpret `eventID`.  To me it should reflect the digital record, i.e. `eventID` is roughly 1 to 1 with a single TW CE

![20240126_114521](https://github.com/SpeciesFileGroup/taxonworks/assets/22600/7e38948e-61b0-4144-81e5-fd8904d37b4e)

Thoughts?

**Comment by LocoDelAssembly** [comment]
Please clarify if `fieldIdentifier` is actually `fieldNumber`? ( https://dwc.tdwg.org/list/#dwc_fieldNumber, currently mapped as verbatim_trip_identifier )

`eventID` is mapped as `TripCode` identifier and the namespace is either assigned from non-standard `TW:Namespace:eventID` field, or from the auto-generated per import dataset one (there was a bug with this one https://github.com/SpeciesFileGroup/taxonworks/commit/73b187deb60c1c4568904da90bfe7e40fe4a975b)

At present it is `eventID` that serves as a way to detect that two events are the same, scoped either to a specific `TW:Namespace:eventID`, or a import dataset-specific namespace. When a match is found, existing CE is used rather than creating a new one and merge data.

Proposal is new namespace, probably global (although would break stuff), to identify CEs?

**Comment by mjy** [comment]
Sorry for label confusion, yes `fieldNumber`

**Comment by mjy** [comment]
Making a note that `TW:Namespace:eventID` matches against `Namespace#short_name`

**Comment by mjy** [comment]
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/2852.

**Comment by mjy** [comment]
* [ ] map eventID to new identifier type in DwC importer
* [ x ] map eventID identifier to dwc_event_id
* [ x ] map verbatim_trip_identifier to dwc_field_number
* Namespaced fieldNumbers are Identifier::Local::TripCode
* eventID defined as proposed on paper ^
* [ ] revisit existing eventID data (largely AntWeb)

**Comment by mjy** [comment]
Finished, add individual issues where needed.
