### ISSUE TITLE
[Bug]: Last updated text for leads only refers to when the *root* node was last updated

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3884]
### Steps to reproduce the bug

```bash
Users probably expect it to mean the last time anything in the key was last updated (not just the root node/metadata), at least that's what I would expect. I expect the same issue is happening with last_updated_by (that what we're displaying is really just "who was the *root* node last updated by?").

We're currently displaying the root's last_updated value at:
 /leads/list
 /leads/ (recents list)
 /tasks/leads/show (the list of keys)

And also the list of keys in the pr for a leads hub.
```

### Environment

Development (docker)

**Comment by kleintom** [comment]
Could I get some feedback here? I'm considering two approaches:

1) Here's a query that returns:
* `updated_at` for the key (not just the root node)
* `updated_by` for the key, both id and user name
* couplets count
* otus count for the key
```ruby
roots = Lead.find_by_sql("
WITH leads_updated_at AS (
  SELECT
    roots.*,
    COUNT(DISTINCT otus_source.otu_id) AS otus_count,
    MAX(otus_source.updated_at) AS key_updated_at,
    (COUNT(otus_source.id) - 1) / 2 AS couplet_count
  FROM
    leads AS roots JOIN lead_hierarchies AS lh ON roots.id = lh.ancestor_id
      JOIN leads AS otus_source ON lh.descendant_id = otus_source.id
  WHERE roots.parent_id IS NULL
    AND roots.project_id = #{sessions_current_project_id}
  GROUP BY roots.id
)
SELECT leads_updated_at.*,
         updaters.updated_by_id AS key_updated_by_id,
         users.name AS updated_by
FROM
  leads AS updaters
    JOIN leads_updated_at
      ON leads_updated_at.key_updated_at = updaters.updated_at
    JOIN users
      ON users.id = updaters.updated_by_id
ORDER BY leads_updated_at.text
")
roots.map { |r|
  r.updated_by_id = r.key_updated_by_id
  r.updated_at = r.key_updated_at
  r
}
```
Those are all things we want when displaying a list of keys (otus count isn't necessary at this point but nice).

2) Get each of those data items one at a time, for each key at a time, using
```ruby
 def key_updated_at
    root.self_and_descendants.maximum(:updated_at)
  end

  def key_updated_by_id
    last_updated_node = Lead.find_by updated_at: key_updated_at
    last_updated_node.updated_by_id
  end
```
and more queries using `self_and_descendants` to get the couplets count and the otus count. For the number and size of the keys we'll have maybe that's not a huge deal, but still pretty inefficient.

I have a pretty strong preference for solution 1, but wanted to see how you feel about the query, I guess just its length - I don't actually think this is a "big" query, I'm just not seeing many similar-looking queries offhand, though I assume they're out there in different forms. I can work on rails-ifying it if you feel good about going that route (though I'm not sure how yet, maybe arel will be needed?).

Also how do you feel about the `map`ping I do above? It doesn't update a root node's updated_at/by values in the *db* with corresponding values for the whole key, but it does pass them around the code in an object representing a root node from the database. It's fine if we don't want to do that, it's just a little more involved passing around/using/updating separate new attributes like `key_updated_by/at`.

p.s. I assume it's technically possible that two threads could update different nodes of a key at the same timestamp time, so there's an issue concerning which most-recent-updater to use in that case - I'm ignoring that.

**Comment by kleintom** [comment]
> I assume it's technically possible that two threads could update different nodes of a key at the same timestamp time

On second thought, is that possible? Now I'm thinking it shouldn't be. But maybe an update on multiple nodes could result in all the nodes having the same timestamp? This isn't really a big issue here, but I'm curious.

**Comment by mjy** [comment]
@kleintom 

A couple of dev guidelines (perhaps these need to migrate to Docs) for the "Handbook":

* Excellent unit-test coverage makes diverse approaches palatable.  I.e. if you define the expecations of your methods with well thought out examples in specs then whether you use SQL or native ActiveRecord becomes much less of an issue
* Please try to keep SQL generic, we do use PG specific syntax in some cases, I intended to comment on this loudly if so.

* I'd prefer not to mock in `updated_by` attributes, too much potential confusion in debugging.  If I understand it correctly this query is a "read" to get a couple specific attributes per root Lead, for summary purposes.  I feel the `map` is a little overkill here.  If it was to get objects en-masse to `update()` then that would be a different story (but in this case incorrect, because we don't want to sync times).

And a couple of notes:

* I do a lot of complex query aggregation in the lib/queries/quiries, including using a hacked-together "WITH" pattern, this may/not be useful for your reference
* Rails 7.0, of which we have a branch and could in theory move to shortly, has native `with()` support, which is going to be big.

> p.s. I assume it's technically possible that two threads could update different nodes of a key at the same timestamp time, so there's an issue concerning which most-recent-updater to use in that case - I'm ignoring that.

Updates like this almost certainly don't  happen AFAIK.

**Comment by mjy** [comment]
@kleintom we can close, correct?
