### ISSUE TITLE
[Bug]: Edit CE - saving any edits on CE record prompts error

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3912]
### Steps to reproduce the bug

```bash
Trying to edit any CE record, I get a prompt after clicking Save: Text: Can't be blank
There is no indication what text or what cannot be blank.
In this instance I was changing the CE tripcode. In another CE record updates such as adding verbatim locality notes prompted the same error message.
I deleted the record and re-entered it with similar results.
Issues for CEs ANTC48789 and ANTC48790
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/8d2c7b59-8d0d-4772-a30f-b1f55aa07e2f)

### Expected behavior

If I update a CE record and there is an error, I would like some indication of what the problem is. Something more specific than "can't be blank"

### Environment

Production

### Version

v0.40.1

### Browser Used

Version 123.0.6312.106

**Comment by jlpereira** [comment]
This was fixed last week, not in production yet.

**Comment by AntWeb-org** [comment]
That was an autofill issue in the CSD. This issue is an error prompt and edits not saving in the CE.

**Comment by jlpereira** [comment]
This issue is related to the label object. `text` is an attribute of label object. The interface was trying to save the label even though it was not assigned.
This problem was reported to me directly, there is no issue created here. But it's fixed and it will be available on the next release. In the meantime, you can continue editing and don't have to worry about this problem, your changes will be saved and you only see this warning when you're creating/editing a collecting event that doesn't have a label.

**Comment by AntWeb-org** [comment]
O.k., I'll wait for the next release - thanks José
