### ISSUE TITLE
Task-Filter COs: field synchronize updates remain in filter results

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3998]
### Feature or enhancement

After I update, for example, 3 out of 50 COs using the "field synchronize" tool after a filter search, then select "Back to filter", I only see the 3 COs updated by the field synchronize tool. When I refresh the filter the 3 same COs remain and the filter parameters seem to disappear. 

When I select "Back to filter" I would like to see all 50 results from the original filter including blue check mark of those selected to update. When I refresh the filter, the original filter parameters should maintain and I should only see the remaining 47 COs that have not been updated. Right now it seems counter intuitive since the filter should not include the updated COs.

### Location

Task-CO filter

**Comment by mjy** [comment]
@jlpereira Are we sending the checked boxes or the original query that got us here by POST?  Should be the latter.

**Comment by jlpereira** [comment]
> @jlpereira Are we sending the checked boxes or the original query that got us here by POST? Should be the latter.

It depends, if the user uses the radial linker on the right, it will operate on the selected COs. If they use the one on the right, it will use the query.
To make it work the same way on both sides, we could eliminate all _id parameters, we would have to look for the type of parameter depending on the filter

**Comment by AntWeb-org** [comment]
I do not understand, "It depends, if the user uses the radial linker on the **right**, it will operate on the selected COs. If they use the one on the **right**, it will use the query."

I did use the radials on the right though.

**Comment by jlpereira** [comment]
When you use the radial linker on the right, only the object IDs will be passed as a parameter to the task. This is why when you press back, it loads the filter with these objects. However, if you use the left radial, all the filter parameters will be passed. When you press the link to return to the filter, it will reload all the results

**Comment by AntWeb-org** [comment]
The radials on the right change/update all COs whether they are blue checked for updating or not, is that correct?

**Comment by jlpereira** [comment]
> The radials on the left change/update all COs whether they are blue checked for updating or not, is that correct?

Yes, they operate on all results. In this case the Radial linker does not update or change anything, it simply opens tasks with the parameters. If you use the one on the left, it will pass all the filter parameters to the task, if you use the one on the right, it will only pass the id of the objects as a parameter. To give an example, if you opened the Field Synchronize task from the radial linker:

Radial linker on the left:
`/tasks/collection_objects/filter?per=50&geo_json={"type":"MultiPolygon","coordinates":[[[[-64.6875,-44.087585],[-64.6875,-30.751278],[-55.546875,-30.751278],[-55.546875,-44.087585],[-64.6875,-44.087585]]]]}&extend[]=dwc_occurrence&extend[]=repository&extend[]=current_repository&extend[]=collecting_event&extend[]=taxon_determinations&extend[]=identifiers&exclude[]=object_labels&page=1`

Radial linker on the right:
`/tasks/data_attributes/field_synchronize?collection_object_query[collection_object_id][]=1475377&collection_object_query[collection_object_id][]=1476242&collection_object_query[collection_object_id][]=1476984`

As you can see, parameters are different. Because you're operating on different things, one operates over filter results by passing all setted parameters and the other operates over selected objects. So when you press `back to filter` it will load the filter with these parameters.

Currently, there are two possible solutions for this

The first is to use the radial linker on the left and only update the rows you want in the Field Synchronize task. The other is to continue using the one on the right, but when you open the radial linker, right click on the Field Synchronize slice and click open in a new tab. This way you will open the task in another tab and keep the filter open in a different tab. When you finish working on the Field Synchronize tab, simply close it and refresh the filter results in the other tab.

**Comment by AntWeb-org** [comment]
Thanks José - I think right clicking on the field synchronize slice is my best bet. Thanks for the clarification.
