### ISSUE TITLE
[Bug]: unjustified emendation relationship does not take author infomation

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#4022]
### Steps to reproduce the bug

```bash
I am curating many names without author. Many of them are simple misspellings in which cases the migration could not detect the kind of relationship, so it used the "unavailable or invalid, linked to" one.
In those situations, I only change the unavailable relation for the misspelling. The name automatically gets the [sic] end and the author of the valid Taxon Name is added. 
I expected this also to happen with the "Unjustified Emendation" relationship. When I select it, instead of the unavailable one, it gets the [sic] but does not add the author of the valid name. 
Is it a bug? Or Am I wrong?
```

### Screenshot

![image](https://github.com/user-attachments/assets/360b92c3-37ff-4d36-a839-0389a0920032)

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
unjustified emendation is an available name, which has its own author and year of publication. Each emendation should be double checked, since it could be just a misspelling. A deliberate change of the name and presence of both spellings in publication is required to qualify for unjustified emendation status. Unjustified emendation is also an objective synonym. If in prevailing usage, it could qualify to the status of justified emendation, in this case it will became a corrected original spelling, which does not has its own author and year.
