### ISSUE TITLE
[Bug]: Field Number validation is too strict

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#4061]
### Steps to reproduce the bug

```bash
1. When I have a verbatim Field Number
2. And I try to add the identifier 
3. And they don't EXACTLY match (e.g. TCM-XXXX vs. TCM XXXX)
4. Then the save fails.
5. This is too strict and should be reverted to the old validation which was much less strict.
```

### Environment

Production

### Version

0.44.0

### Browser Used

Firefox

**Comment by mjy** [comment]
Going to re-factor this to enhancement/question, because behaviour is what is intended. The change was made in response to improving the behaviour of the DwC importer.  There, when conflicting information is given, it means someting is not quite alligned, as in your example.  I can see the benefit and constraints of both approaches.  Frankly we added this constraint with the anticipation we would wait for feedback like this.  Let's get at least two other voices to chime in here and we'll move forward based on the concensus.

**Comment by bpescador** [comment]
I don't understand why there is a check against verbatim. I thought the import of FieldNumber would be as follows: 

fieldNumber
TW:Namespace:FieldNumber
verbatimFieldNumber

In this case, Verbatim is just a record of how the field number was initially recorded.

**Comment by tmcelrath** [comment]
Agreed with @bpescador

**Comment by bpescador** [comment]
I think for all identifiers, including cat. number and field number, there should be a standard 3 field import
