### ISSUE TITLE
Task - Edit TaxonName - plant name subsequent combination. Edit an existing combination generates an error message

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#4079]
I have a plant name. I created a subsequent combination (genus/species). Saved it. Made it preferred. I cannot edit and save this combination before "Preferred" is deleted.

**Comment by jlpereira** [comment]
@mjy It seems to be a server restriction

**Comment by jlpereira** [comment]
Tested and the Interface allows you to edit/delete the combinations, this happens when you try to edit the Preferred name combination, server sends 422 response: "This combination could not be used as a Subject in any TaxonNameRelationships."

I'm not sure if this is the same error that @proceps is getting, but at least that's what I get when I follow the steps.

**Comment by jlpereira** [comment]
Fixed by https://github.com/SpeciesFileGroup/taxonworks/commit/31c4581983469dc3d5efc497a983019c1689e647
