### ISSUE TITLE
[Bug?] Duplicate repository acronyms prevent DwC import

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#4111]
A DwC record import fails where there are two repositories with the same acronym. This is the case for example with 'US': US National Herbarium and University of Stellenbosch.  In order to import records housed at the former, I had to temporarily change the acronym of the latter.

Not sure what the best solution is. Acronyms are not globally unique. Maybe a mapping could be set up in the Settings, as with institutionCode to Namespace?

**Comment by mjy** [comment]
Acroynyms in TW *are* globally unique.  Verbatim acronyms are not. 

Before I poke further, when you said "temporarily change" did you mean in TW, or in the DwC data?

**Comment by camwebb** [comment]
> Before I poke further, when you said "temporarily change" did you mean in TW, or in the DwC data?

I temporarily changed the repository acronym, in TW, of University of Stellenbosch to `UStel`, so that `US` would load to US National Herbarium. I have since changed `UStel` back to `US`.

**Comment by mjy** [comment]
> Acroynyms in TW are globally unique. Verbatim acronyms are not.

Sorry, my mind was on Namespaces, not Repositories when I stated this,sorry for the confusion.

> you must have imported the whole of GRSciColl

Correct, well, as of many years ago.

So, this is not a bug, there are duplicate acronyms in reality.  To resolve unambiguously you can use the `url` attribute of the Repository in your data being imported: the code does this as first check:
```ruby
institution_code.starts_with?('http://') || institution_code.starts_with?('https://')
```
* You'll have to use something like Refine to globally find/replace your values in the import dataset.
* Since our data are old, you may need to reference grscicol to get an identifer value for the TW `url` attribute and use that in the Repository, this will help to merge in new grscicol data too.

**Comment by camwebb** [comment]
Thanks for the solution. Easy to fix.
