### ISSUE TITLE
Print key and api/key interaction with internal key otus/links

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#4145]
I'm not sure if this is a feature request or intended behavior:

1. Create a key that has an otu or link set on a non-leaf (non-root) node.
2. Print the key/serve it via the api

Actual result: the printed key prints the otu else link else the next couplet number: https://github.com/SpeciesFileGroup/taxonworks/blob/8a33c47b570c13a1a06e0d82e3f36abc2c8eb23c/app/helpers/leads_helper.rb#L161-L178

Expected result: all three of those things could be present on an internal lead and displayed somehow.

The use case I have in mind would be something like a key to the species of a family where when you get to a point in the key where a genus is determined you would set the genus otu and/or a link to some external resource for that genus on the lead that determines that genus.

**Comment by mjy** [comment]
Thanks @kleintom. The use of labels a waypoint/signpost indicators rather than leaf/terminal labels is certainly concievable, however I do think the three options are logically distinct enough that it's OK to treat them this way.  Link-wise when I get to the end I want to got to where I am directed, not decide what to do next, so providing an OTU and link-out conflicts a little with this, it sacrifices certainty for "what next".   Let's see what happens when the keys may it into the wild?

**Comment by kleintom** [comment]
> Let's see what happens when the keys may it into the wild?

Sounds good.

I think there's an issue then if somebody does add an otu or link to a non-root lead (there's currently nothing in the editor to prevent this, maybe there should be?): when the key prints it will print the otu/link at that lead instead of the couplet number to go to next. Example here: https://sandbox.taxonworks.org/tasks/leads/print?lead_id=9
