### ISSUE TITLE
Task - Uniquify people

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#428]
* vue app to page through people that have identical or similar(?) names
* select people, merge them together by updating roles
* bonus- another checkbox to merge alternatve values

**Comment by jrflood** [comment]
What is the starting point of the search for people?  Autocomplete?  Find all cases satisfying identical and/or similar ?   Some other method of specifying one name to find matches against?

**Comment by mjy** [comment]
@jrflood Endpoint is `/people.json`. Create filter logic in a new file `lib/queries/people/filter.rb`.  Perhaps use the corresponding filter.rb in `tag`.

It's up to you to determine what might be an efficient process for doing the task.

**Comment by jrflood** [comment]
![screen shot 2018-06-05 at 1 00 24 pm](https://user-images.githubusercontent.com/5349955/40993978-95cd517e-68c0-11e8-9f70-c922a9a7249a.png)
![screen shot 2018-06-05 at 1 01 59 pm](https://user-images.githubusercontent.com/5349955/40994006-aafd1bba-68c0-11e8-9574-e75070705de3.png)

**Comment by jrflood** [comment]
![screen shot 2018-06-05 at 5 27 50 pm](https://user-images.githubusercontent.com/5349955/41006102-ce57ed36-68e5-11e8-80cd-30b907d52df8.png)
![screen shot 2018-06-05 at 5 30 07 pm](https://user-images.githubusercontent.com/5349955/41006202-2170afa8-68e6-11e8-88b2-1caa19c7e420.png)

**Comment by jrflood** [comment]
The person search is not necessarily simple. Exact match of the last and first name with specified roles is straightforward.  How flexible should the search be?  Obvious variants are: Last name only; Last name with first initial of first name; last or/and first name starts with Xxx*; any of the selected roles or no roles.

**Comment by mjy** [comment]
It's up to you how the client queries  db.  Remember you can make multiple
queries from the client, you don't have to do one query with crazy logic in
it.

**Comment by jrflood** [comment]
Merge People Options

Common baseline:
Select exemplar person
Specify options and select merge candidates 
Select people to be merged with the exemplar from checkbox list

Proposal A
Exemplar assumes the roles of the selected people
Change person ID to exemplar person ID in instances of use of merged person ID — very tedious
Delete each merged Person 

Proposal B
Same as A, except mark merged people as merged with exemplar instead of deleting them.

Proposal C
Same as A, except make selected matches an alternate value to the exemplar

**Comment by jrflood** [comment]
Aside from filling out the cases for tests. this task seems complete enough for user feedback/critique.  Known issues: comparison blocks between people are rendered JSON vs pretty; possibly there should be a back-end/server-side initial search function to find probable duplicates (a la Levenshtein) instead of user input alone.

**Comment by mjy** [comment]
Thanks! @jrflood @TuckerJD What's the status of unit tests for the `merge` related model code?

**Comment by jrflood** [comment]
There is a strange behavior in the both unvetted person test where the merging unvetted person becomes mysteriously vetted for no apparent reason. The merge result becomes a vetted person therefore and the test expecting an unvetted person fails -- the only failure when running the debug server. The tests fail about 50% when using the run server oddly.

**Comment by TuckerJD** [comment]
Still outstanding on the `#merge_with()` front:
- [ ] What to do when there are year attributes in both l_person and r_person.
- [ ] What to do when there are (prefixes or suffixes) in both l_person and r_person.
- [ ] Something else, which I don't remember right now.... I'll edit this when I remember.

**Comment by mjy** [comment]
There are some optimizations necessary, and maybe(?) a duplication bug in #merge
