### ISSUE TITLE
Data - OTU - Otu name

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#440]
When both TaxonName and Name are provided, change the order in the display:
TaxonName first followed by the Name

**Comment by mjy** [comment]
For requests like this that at first glance are cosmetic please let us know
why we should do this, I.e. What's the thinking?

From my perspective you are referencing an OTU, if I went to the trouble to
give it a name, maybe I want that first?

**Comment by proceps** [comment]
In most cases I have either TaxonName or Name. I give both of them, when I have two or more OTUs. For example
Aus bus (from Canada)
Aus bus (from USA)
Aus bus (associated with Oak trees)

if I have just a TaxonName or just the Name, I do not have any problems

**Comment by reptalus** [comment]
I would like to make an example fits with my stuff, I would prefer to have Taxon Name before the (Otu) Name when both of them exist for a reason of hierarchy or in other cases because historically ordered.

Let make an example: some group of organisms not well taxonomically established (e.g. phytoplasmas) are know with the OTU Name which is related to a DNA marker, however we can have different kind of DNA markers (according to different schools of thought),  but when the taxonomy is established for a species (=groups of sequences) then the Taxon Name became more important and I would like to see it before.
