### ISSUE TITLE
Branch development: Most geo object tests fail.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#537]
Removing `$project_id` at the end of `shared_geo.rb` causes subsequent object construction to fail with `ActiveRecord::RecordInvalid: Validation failed: Project can't be blank`.

**Comment by mjy** [comment]
@TuckerJD I am completely refactoring the shared geo context to get rid of the many global messes in there.  Made it a fair way along, might be able to post today.

**Comment by TuckerJD** [comment]
OK, I'll close this.

**Comment by mjy** [comment]
Leave it open, I almost opened it last nite.  I'll track progress here and try to write a post-mortem explaining what went wrong.

**Comment by mjy** [comment]
# Remaining

* Still haven't fully looked at breaking out pieces of shared_geo.  In particular the model only bits are a reasonable target, as is the bits that were 'simple world'
* Many of the shared geo let blocks are only used in model tests, and will require `by:` and `project:` assignments for more robust long term use.

# The good
* The tests themselves provided nice coverage of the funtionality, though some of the tests could be refactored out to not duplicate the core tests.  This made it possible to refactor the test world with relative confidence (though in general we don't want to be doing this).
* Use of uniquely named lets() (e.g. `tn_abra` rather than `t1`) within a "build a complex set of data) helped to build a mental picture of what was trying to be expressed
* The pertinent tests were nicely grouped/identified with `group: [:geo, :shared_geo]`.

# The bad

## Critical issues
* With the exception of the base support files globals (and coming in 5.2 use of `Current`) should never be referenced, they need to be completely hidden by accessors/helpers. Their use makes it impossible to track state properly, and lead to false positives in the setup.  For example this was evident in that many of the `let()` statements missed including `project: geo_project` seemingly by accident, as their presence/absence was inconsistent, but since the global was set in error they tests were "working".  Various of these errors were caught in the 5.2 branch when we refactored to use `Current` and some tests failed because the assumed state was not what it appeared to be.

## Big issues
* `let()` containing nested object creation, this was really hard to refactor. 
* An excess of setup data. I originally thought this was less important, but it's critical we express as little as possible, do as little setup as possible. For example, why does `co_a` need 7 determinations?  The combinatorics behind testing 7 things in different worlds greatly overloads what we have to understand about that single object, and all the ways it can affect our "world".    Another example- the old `area_<object>' let blocks used only to reference an associated geographic item, it's creation is unecessary, just reference the geographic item directly in the spec.  
* Too much stuff in shared_geo.  I realize it was due for a refactor, but in general, it's an example of too many different things going on in one place.  For example it creates shapes and ApplicationRecords and provided single-use contexts for multiple different specs.  It will require some further breakdown and organization.

## Medium issues
* A commented human-readable description of what the world looks like would have helped.  
* Using `where()` in a let block.  This is a big warning light that something is not being factored out correctly.
* Don't include multiple expectations while linting setup, decouple them, it helps to track down which of the multiple possible worlds are wrong, whereas together the first fails, and the rest tell us nothing.
* Do not use `begin` and `end` as comment blocks/to isolate other blocks with no further meaning. If they really reflect intended/restricted use isolate into a shared concern. 
* Let blocks that a referenced a single time are largely useless, their functionality should be replaced inline.  For example `area_linestring`.
* Let blocks that are used in a single spec should not be in the shared world.  For example `line_string_a` (== `gi_line_string` now).  Or, minimally, anticipated re-use should be forked out to its own concern/module.
* Cleanup let blocks that use assignment to variables to debug removing the variables, or let blocks in general.  In general don't leave breakpoint aids in committed code.  For example `gat_list`.  Use linting if you want to repeat the functionality of something like gat_list.

* Cleanup no long used let blocks.  Before a final commit do a once over to confirm all the blocks are being used.  For example `area_r2`, `co_a_otus` were not used.
* The overal lines of code in the shared context is too many.  
* Repeated let() blocks, for example `area_rn4`
* Mixing the "types" of let blocks.  This is a little trickier and might not follow a single rule, but I'm guessing that an A, A, A then B, B, B pattern is easier then A, B, A, B, A, B to maintain.  For example A might be a Taxon name, and B might be a related OTU.

## Minor nitpicking
* Use of FactoryBot when plain old creates are shorter
* Use the helper `by: geo_user`
* Who was Joe? `let(:joe) { geo_user }`

## Other
* Whitespace and indenting rules need to be locked down.  In Rubymine -> preferences -> Editor -> Code Style -> Ruby -> Other (tab) we need a shared set of options.
