### ISSUE TITLE
unable to destroy taxon

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#56]
Was TW-397. This requires some discussion as to the behaviour of a destroy request-

Considerations:

* If there are descendants, what happens to them? Are they moved to the parent of this taxon?  Also destroyed?
* What happens to the OTU that only has a link to the taxon name?  Possibly- take that cached name for that taxon and put it in Otu#name.
* Do we allow for a delete when annotations and related data would destroyed as well (e.g. TaxonNameClassifications, TaxonNameRelationships, Tags, etc.), or should we require all related data to be deleted first, then allow deletion?

**Comment by mjy** [comment]
@proceps When you get a chance chime in with the behaviour that you would desire in this case. I.e. what do we do for destroying leaf nodes, parent nodes, etc.  How far should things cascade.

**Comment by proceps** [comment]
We should delete only if nothing is linked to the taxon. May be only OTU, but nothing is linked to this OTU.
Otherwise I see the only solution is to merge duplicate records. This should be done as universal tool. Duplicate sources, collecting events, taxon names, etc. All linked records should be moved from one TaxonName to another, after that the empty Taxon could be destroyed. I cannot think of any situation when someone will need to delete a taxon with all related data (only if it was created for testing purposes, but we have a sandbox for this).

**Comment by mjy** [comment]
What do we mean by "nothing"?  For example if
@taxon_name.taxon_name_authors.count.any?, but that's all, do we delete the
name and the associated roles (obviously not the people)?  What about if it
has a citation?

**Comment by proceps** [comment]
If I say we can delete a citation, the next question will be if the name has 5 citations, 20 citation or more. I can only say, if it is one citation, it is easy enough to delete this citation manually. If more citations are provided, it is probably make more sense to move this citations to another taxon (or OTU). Original citation, roles probably could be deleted with a taxon. Again, the only reason when I need to delete a taxon in my database, when I found a duplicate record and I have to take care to preserve all other associated information. It is painful, because I have manually to go to each associated table. May be it could be semiautomated merge. For example, this TaxonName has 5 citation, 2 authors, 3 illustration. When you merge, do you want to transfer everything or illustration only, or illustrations and citations. It can also automatically check that the same citation already exists in the second taxon, the citation could be safely deleted in the duplicated taxon. All transferred relationships could also be tagged for manual verification after the transfer.

**Comment by mjy** [comment]
I think this is likely the key point: `the only reason when I need to delete a taxon in my database, when I found a duplicate record and I have to take care to preserve all other associated information`

**Comment by mjy** [comment]
Combination has been updated to allow for destroy, it will destroy the taxon name relationships that are used to compose it (and, perhaps not in a good way, all the other relationships).  Are there relationships there that we need to maintain, or should consider?

**Comment by mjy** [comment]
There is another reason to delete a name: `I added a name in error, i.e. I thought it was part of my target group, but it wasn't`.

Note that, at least in production, the reason `I was experimenting` is not one we should expect.

**Comment by mjy** [comment]
As a note- a Taxon can be destroyed if nothing is attached to it.

**Comment by mjy** [comment]
Closing this for in lieu of more specific proposals for merging names.  Names can be deleted, but only if they are empty.
