### ISSUE TITLE
DATA: Source: Edit: convert verbatim to BibTeX not possible

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#624]
I added a verbatim source and added a citation unter a new genus.
At this protonym citation appears a note with dusky pink background saying "Source is verbatim, requires parsing".
If I go do DATA: Select this source/Edit, I can only edit the verbatim text, the radio button for BibTeX is disabled.

**Comment by mjy** [comment]
Verbatim will indeed not let you provide author year, this is intentional
and won't be changed.  We're doing this to *strongly* encourage people to
use BibTeX format, and to not further confuse the logic we'd need to add.
You can think of the Verbatim type as basically an import option.
Hopefully once we get some parsing in there it will become more useful.

I'd encourage you to check for Google citations BibTeX format of the
Source, in many many cases this can be found, then the BibTeX tool can be
used.

**Comment by proceps** [comment]
I can confirm, that etymology of a taxon does not autosave in Edit Taxon Name task. Only if you click Save button. But the save button is only on the top of the page.

**Comment by mjy** [comment]
On that form you can always type `ctrl-s`

M
