### ISSUE TITLE
genus group / supergenus / infratribe

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#645]
Genus groups from OSF currently appear as supergenera in TW, saying that type species are not selected, while they in fact have type genera.

A genus group (a real group of genera, not a genus-group taxon) is a family-group taxon, see ICZN Article 15.1. "The family group encompasses all nominal taxa at the ranks of superfamily, family, subfamily, tribe, subtribe, and any other rank below superfamily and **above genus** that may be desired".

Most of these groups in Tettigoniidae (and probably all Orthoptera) are quite old, and have been established without explicit rank or explicitly as group of genera, e.g. "Gruppe Turpiliae" Brunner von Wattenwyl, 1878 (with type genus Turpilia). Many of these groups have been elevated to subtribes, tribes, or subfamilies.

So the rank "infratribe", as @mjy suggested (e-mail exchange with @mbeckman on Monday) would be indeed more appropriate, if "genus group" does not exist in TW.

In OSF these taxa based on generic names usually end in -ae, with very few exceptions in Tettigoniidae (there are some more exceptions, including informal names, in Acridomorpha).

**Comment by mjy** [comment]
We all understand the issue I think. In my opinion the crux of this is the terrible confusion of labels and homonymy that came with OSF used the label "genus group".  In that scenario we had:

* The label "Genus group" for a name that was neither a genus, nor the ICZN labelled "Genus group", as in "Genus group names"
* A name in "Genus group" rank (sensu OSF) that competed for priority with a Family group name, terribly confusing at first read.

Moving forward I think we can do better by using labels that are not homonymous.  This is a good opportunity to clean up these issues, so that the next time the data need to be migrated we don't face these missunderstandings at their various levels.  It's great to see that most of the names in question adhere to family group endings.

**Comment by mbeckman** [comment]
Thank you, Holger, for pointing me to this discussion. Matt and I have been discussing which types of issues should be in GitHub vs GitLab. I did not find this discussion the other day when I was reviewing open issues, most likely because there was no label. (Just added data migration label -- though this probably belongs in GitLab.)

So with all that has been said, I will attempt to import all Genus Group rank (RankID = 22) taxa to infratribe.  However, there are several issues with this rank as well:

There are currently 143 names in SF with this rank, 102 of which are monomials (65 ending in '-ae'), leaving 41 compound names of one sort or another. The compound names will probably not be considered valid because of more than one word. I'm not sure about the other 35 or so monomials with other endings.

Invalid names cannot have valid subordinate taxa and probably cannot be in a type genus relationship.

Suggestions?

**Comment by proceps** [comment]
Invalid names cannot have subordinates, they will be synonyms of something else and all subordinate taxa will be moved there.
On the other hand, they are perfectly ok in type genus relationships.

**Comment by typophyllum** [comment]
I was not yet aware of GitLab when I subbmitted this. There are the followig types of genus groups in OSF:

1) Ending in -ae (e.g. Turpiliae with type genus Turpilia)

2) Ending in -a (e.g. Cosmophylla with type genus Cosmophyllum, Microcentra with type Microcentrum)

3) Name identical with type genus name (e.g. genus group Axylus Ingrisch 2015 and temporary name Dichopetala)

4) Binomials with genus name and group (e.g. Platycleis group) - these can easily be replaced by type 3

5) Other binomials (e.g. temporary names Grupo chileno central, Grupo patagonico ) - only 3 cases, could perhaps be removed

I guess there are no problems with types 1 and 2. I don't like type 3, but it's analogous to the names of species groups. Can this type be migrated without problems to TW? We can probably get rid of types 4 and 5. Are there further types, Marilyn? Any problems with the "temporary names" which have subordinates (probably very few cases)?

**Comment by mbeckman** [comment]
Thanks, Dmitry. In light of what Dmitry said, I propose changing the rank to infratribe. Those compound names will become synonyms of their parent. The type genus relationship can then preserved.

**Comment by mbeckman** [comment]
Is there a convention or code requirement for a particular ending for an infratribe?

**Comment by typophyllum** [comment]
The Code regulates only suffixes of family-group names from subtribe upward.

I think the compound names of type 4 should be converted to type 3, as synonyms of their parents they wouldn't make any sense.

**Comment by mbeckman** [comment]
I would prefer that you change the compound names in OSF rather than me doing it in the import program (I can give you a list if you like). There is potential for error when I do it programmatically. After I get the current data cut (data from around 7 November 2018) imported, I'll get a new version of the data that will hopefully have your changes.

**Comment by typophyllum** [comment]
Yes, please send a list, so I won't overlook any.

**Comment by typophyllum** [comment]
Thanks for the list. The compound names no longer exist, except the three groups under Tristirini, which cannot be deleted because they are included in a key (now they are synonyms with access code 1). Most of these compound names were unnecessary junior synonyms of perfectly good tribe names, the others are now identical with the corresponding genus names (type 3 according to my earlier comment today).

I found another type, ending in -i (e.g. Apteropeoedi with type genus Apteropeoedes, subsequently emended to Apteropeoedini).

**Comment by mjy** [comment]
I think we can migrate/move this issue to the Gitlab tracker?  This seems
very specific to data now?

**Comment by mbeckman** [comment]
I think we've resolved this issue for now. If not, re-introduce it in GitLab.
