### ISSUE TITLE
Browse source: strange behavior

### ISSUE THREAD

**Issue by lucfusu** [SpeciesFileGroup/taxonworks#764]
Hi,
In Browse source if I search Fusu 2018 I can find the paper I just added.
If I search for South Korea 2018 I can see it again.
If I search for South Korea I don't see it. When I sort by year the most recent is 2016.

**Comment by mjy** [comment]
Thanks much @lucfusu!  We'll investigate and see if we can make the results more consistent.

**Comment by mjy** [comment]
@lucfusu You don't find the result because there are too many results for those search terms (it caps at 500).  I've tweaked the results to sort by recent additions, this doesn't solve the problem fully, but it does get more pertinent results slightly closer to the top.  So- the solution is to provide more specific search terms, but also when the change gets added you should get your recent hits.

**Comment by lucfusu** [comment]
Hi,
Thanks.
I thought it is this, since with South Korea 2018 it works (more specific search terms). Still the behavior is strange because if I sort by year I should see it at the top. I understand that the screen shows 500. Then with year ascending I will not see mine as it is beyond 500, but with year descending it should be present.
Shall I understand that 500 is a sort of buffer and it is simply rearranging the same 500 ? I suppose this is something to difficult co correct, right?
All the best,
Lucian


Dr. Lucian FUSU, lecturer

'Al. I. Cuza' University, Faculty of Biology

Research Group in Invertebrate Diversity and Phylogenetics

Carol I bd. no. 11

700506 Iasi, Romania

http://www.bio.uaic.ro/cercetare/grupuri/nevertebrate/index.html

________________________________

**Comment by mjy** [comment]
You're right, it's a buffer, it non-deterministically loaded the first 500 records that hit.  Since we split the keywords ("South", "Korea") the general search doesn't get your record.  In the fix that we'll post (sometime today likely) I've changed the order to be deterministic (ordering by modification date), so at least in your specific scenario you'd see the record-  note that you wouldn't find your record if it was 500+ records old.  Likely need to thhink of some other params to add there, the current one was just to get, say %90 of use cases.

**Comment by lucfusu** [comment]
Hi,
Thank you very much for the explanation. At least if it cannot be fixed, there should be a note somewhere, that you get only 500. For example if I want to know how many papers were published with Trichogramma in the title (for statistics lets's say) I cannot, right?  I tried and it is above 500. Is there another way?


Dr. Lucian FUSU, lecturer

'Al. I. Cuza' University, Faculty of Biology

Research Group in Invertebrate Diversity and Phylogenetics

Carol I bd. no. 11

700506 Iasi, Romania

http://www.bio.uaic.ro/cercetare/grupuri/nevertebrate/index.html

________________________________

**Comment by anadm** [comment]
Perhaps a warning could be displayed:
"Your search returns above 500 results. Please use more filters".
Sure, this may mean the help page in that screen must include information
on filters.

**Comment by anadm** [comment]
probably default sorting should be by publication date, not latest additions

**Comment by mjy** [comment]
The form already lists the total, we will make this more prominent. Publication date is not available for verbatim references.  You can use the columnar sort to add a filter to the table (but see below).

Thinking through this we need to call this task "Search sources" not  "Browse sources", I'm going to rename it.  Search and browse being two different concepts, the former you know the target, the latter you don't. The intent of this form is that you know the target (you know the keywords etc., you want to find something quick).  A task that lets you browse sources is very different, it includes ways to find general sets (search in a specific field, limit results, etc.), navigate through them, filter them further, etc.

**Comment by anadm** [comment]
Agreed, will update in reference
