### ISSUE TITLE
Collection Object Filter by - use DWC occurrence result as table

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#82]
Change the result table to reference dwc_occurrences.  This part is easier.  Less easy is generating the map result.  Essentially need mechanism to dynamically add data to map after successfull Ajax call.

**Comment by jrflood** [comment]
This page DOES still have the edited polygon problem I mentioned to @mjy last week.  Creating a new polygon and hitting [Set area] works correctly, but adjusting the polygon does not.  This is a previously known problem that wasn't fixed due to late detection and lower priority in view of added functionality in searches.  I have a pretty good idea how to fix it.

**Comment by mjy** [comment]
@jlpereira can you modify the download button js to act identically to "find", but reference "download"?

**Comment by mjy** [comment]
Done in new filter.
