### ISSUE TITLE
Browser request timeout before bulk upload finishes

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#897]
When I upload a bulk list of names then the browser request times out before the upload script finishes and I get an error client-side in the browser.

1. When I bulk upload a lot of names from the bulk upload of taxon names
2. Then I hit submit.
3. And I wait for the names to finish uploading.
4. Then I get a timeout error. The script continues in the background, and all names are uploaded, but I don't get the confirmation screen. 

![image](https://user-images.githubusercontent.com/11411328/55358311-b3350480-5494-11e9-800e-47abef806a5a.png)

**Expected behavior**
I should not get a timeout if the script is still running. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production: Cucujoidea Species File
- Sandbox: Cucujoidea Species File (replicated in both environments)
- Chrome

**Comment by mjy** [comment]
@LocoDelAssembly I suspect we can use the new job framework for this.

**Comment by LocoDelAssembly** [comment]
@mjy yes but strongly likely it'll need a supporting model for the import itself or think of using redis outside of containers so all pods are synched. Also it is complicated to handle previews as views access models that are not persisted (when previewing mostly) so views have to be rendered on the ActiveJob-side as well and then stored to be sent later when the user requests the results. Session data needs to be passed along correctly too since both worlds are independent of each other. I've experimented with this but required significant changes on every single batch import (CSRF protection was hard to deal I remember, so views had to be refactored in partials instead of storing the full page and send it when needed). Now thinking if we could make this work with some sort of proxy for the request so the user can be redirected to a "please wait" page while in the background the request is replayed with much bigger timeout by skipping Varnish and nginx. Need to think more this, would be great if we can come up with a method that requires little to no change to existing code.

**Comment by mjy** [comment]
@LocoDelAssembly Would loading the file as a TW `Document` as a first step make the whole process easier?  

While we have significant batch loading code, it's not an unsurmountable amount. I.e. I think we should not abandon ideas to develop a new framework.  The underlying logic that parses individual columns etc. should still be fine.

**Comment by tmcelrath** [comment]
This is not an issue anymore I don't think?

**Comment by mjy** [comment]
While still potentially an issue for the old batchloads this is not for Checklist format in the DwC importer.

**Comment by mjy** [comment]
Closing as outdated. It may still exist but there are elements of server infrastructure involved as well.
