### ISSUE TITLE
As A DevOp I want tests to run in parallel in Travis

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#907]
@LocoDelAssembly this is fairly high priority.  

Previously I had tests running, but not summarizing correctly, i.e.:
* only report success when all parallel bits finish
* summarize all failed tests

May mean a bash script to handle the summary, was unclear.

**Comment by LocoDelAssembly** [comment]
@mjy @jlpereira yesterday I found a way for Travis to stop recompiling assets on every build (6216ec4c503c9659ed8ddef197c3d8449b24fb08). Considering this a 100+ seconds time save, do you find it risky? By risky I mean the case of having a passing build when it should actually fail, since when alerted by a failed build we can always clear the cache.

@mjy despite git blames you for https://github.com/SpeciesFileGroup/taxonworks/blob/1dc0a1ced599e98581a31bc8a98485ab385fc6ed/spec/support/vendor/vcr.rb#L4 I believe it was probably me and you copied it over when refactoring. Perhaps we could have this setting for dev machines but when running on Travis environment not let them expire? This tends to produce a somewhat noticeable time penalty on everyday first build. Perhaps we could set a CRON (like SpeciesFileGroup/taxonworks_install) and let VCRs refresh for that particular event (TRAVIS_EVENT_TYPE=cron)?

Because of the change in assets recompilation a few extra adjustments will be required to equalize the average runtime of each test worker, so I'll keep merging development and taking measurements. After that parallel_travis would be ready for a pull request to development.

**Comment by mjy** [comment]
Caching should be fairly safe I think.  It's relatively unlikely that a build will pass with a bad cache- as cache/app connection should be quite brittle.

CRON for VCR refresh is likely(?!) pretty safe, we just have to remember it exists.  VCR based tests are somewhat more important in general because they represent wrappers around potentially changing APIs, for example the Crossref API is always changing.

For the record- the next step after getting this to work is to use a containerized build, so the CI is over several indepentant steps:

* CI for container
* CI for assets
* CI for app

Each step depends on the prior, and we can tune when each step is fired.  In theory this would speed things.

**Comment by LocoDelAssembly** [comment]
@mjy I'm thinking that perhaps it is best to leave VCR settings as is, but also set up a **daily** CRON to renew VCRs overnight so the first to push during the day won't get a longtime build (cache is already set up, it is just that as it is currently it expires in 1 day). Do you agree?

**Comment by mjy** [comment]
Sure.  I think it's actually OK to push it to lengthen it somewhat, say 3
days as well.

**Comment by mjy** [comment]
@LocoDelAssembly We can close, right?

**Comment by LocoDelAssembly** [comment]
Sure! Closing it with this comment.
