### ISSUE TITLE
CrossRef parser - the date is parsed incompletely

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#997]
When a citation from ZooKeys is processed, CrossRef returns full date of publication (year, month, day). Only year and date are added to the TW. Please make sure that the day is also parsed (if it is provided).

**Comment by mjy** [comment]
All this processing happens by the gem libraries, not our code.  I'm afraid there (very likely) is nothing we can do.  We are certainly not going to start writing exceptions to individual formats, that's a nightmare waiting to happening.

**Comment by mjy** [comment]
@proceps If you want us to expore this you have to give us explict ways to repeat the problem.

**Comment by proceps** [comment]
Take any publication from ZooKeys and process it with with Citation_to_source task (DOI or just a citation). I checked directly on the web site of CrossRef that the publication is parsed completely, the date is present as year, month and day. When the same citation is processed in the Task, the month and year are inserted into appropriate bibtex fields, but the day field stays blank. I thought may be the field name is misspelled when processing the record, but I could be wrong.

**Comment by mjy** [comment]
After looking at this closer this is not a bug on our side.  Getting more information is an enahancement. Our [ref2bibtex](https://github.com/SpeciesFileGroup/ref2bibtex) gem uses the BibTeX response from Crossref, not the JSON response.  That response does not include the day (see below).

There are two solutions: 
1) Contact Crossref and have them update their response (if day is legal in Bibtex; 
2) Use a different library, one that accesses JSON rather than BibTeX.  

[JSON](https://api.crossref.org/v1/works/10.3897/zookeys.870.32903.figure10)

BibTeX response:

```
"@article{Wu_2019,\n\tdoi = {10.3897/zookeys.870.32903},\n\turl = {https://doi.org/10.3897%2Fzookeys.870.32903},\n\tyear = 2019,\n\tmonth = {aug},\n\tpublisher = {Pensoft Publishers},\n\tvolume = {870},\n\tpages = {33--50},\n\tauthor = {Min Wu and Zhengping Liu},\n\ttitle = {The first proven oxychilid land snail endemic to China (Eupulmonata, Gastrodontoidea)},\n\tjournal = {{ZooKeys}}\n}" 
```
